import type { ProjectKind } from "domains/lifecycle";
import type { EditorField } from "../types/field.type";

const TITLE: EditorField = { key: "title", label: "Название", required: true };
const TASK: EditorField = { key: "taskId", label: "Задача", type: "task", required: true };
const COMMIT: EditorField = {
  key: "commit",
  label: "Проверяемый коммит",
  description: "Точное состояние кода, к которому относится результат.",
  section: "details",
};
const RUN: EditorField = {
  key: "runId",
  label: "Исполнение",
  type: "reference",
  referenceKind: "run",
  section: "links",
};
const EVIDENCE: EditorField = {
  key: "evidence",
  label: "Подтверждение",
  type: "markdown",
  description: "Ссылка на отчёт или описание выполненной проверки.",
};

/** Поля собраны вокруг пользовательского действия, дополнительные сведения раскрываются отдельно. */
export const EDITOR_FIELDS: Record<ProjectKind, EditorField[]> = {
  passport: [
    TITLE,
    {
      key: "purpose",
      label: "Зачем существует проект",
      type: "markdown",
      description: "Какую проблему решает продукт и что важно понимать новому участнику.",
    },
    { key: "audience", label: "Для кого", type: "markdown" },
    { key: "owner", label: "Ответственный" },
    {
      key: "productStage",
      label: "Стадия продукта",
      type: "select",
      options: ["discovery", "prototype", "mvp", "production", "retirement"],
    },
    {
      key: "mode",
      label: "Режим работы",
      type: "select",
      options: ["active", "maintenance", "paused", "archived"],
    },
    { key: "scope", label: "Границы продукта", type: "markdown", section: "details" },
    { key: "constraints", label: "Ограничения", type: "markdown", section: "details" },
    { key: "summary", label: "Что происходит сейчас", type: "markdown", section: "details" },
    { key: "nextStep", label: "Следующий шаг", type: "markdown", section: "details" },
    {
      key: "focusPlanId",
      label: "План в фокусе",
      type: "reference",
      referenceKind: "plan",
      section: "links",
    },
  ],
  plan: [
    TITLE,
    {
      key: "goal",
      label: "Какой результат хотим получить",
      type: "markdown",
      description: "Опишите наблюдаемый результат, по которому можно принять план.",
    },
    {
      key: "status",
      label: "Состояние",
      type: "select",
      options: ["draft", "planned", "active", "paused", "completed", "cancelled"],
    },
    { key: "owner", label: "Ответственный" },
    { key: "scope", label: "Объём изменений", type: "markdown", section: "details" },
    { key: "summary", label: "Текущее состояние", type: "markdown", section: "details" },
    { key: "nextStep", label: "Следующий шаг", type: "markdown", section: "details" },
  ],
  stage: [
    TITLE,
    { key: "planId", label: "План", type: "reference", referenceKind: "plan", required: true },
    { key: "outcome", label: "Результат этапа", type: "markdown" },
    {
      key: "criteria",
      label: "Критерии готовности",
      type: "markdown",
      description: "Что должно быть проверено перед приёмкой этапа.",
    },
    {
      key: "status",
      label: "Состояние",
      type: "select",
      options: ["planned", "active", "accepted"],
    },
    {
      key: "acceptance",
      label: "Основание приёмки",
      type: "markdown",
      description: "Обязательно для принятого этапа: результаты проверок и оставшиеся ограничения.",
    },
    { key: "order", label: "Порядок этапа", type: "number", section: "details" },
    {
      key: "dependsOn",
      label: "Зависит от этапов",
      type: "multi",
      referenceKind: "stage",
      section: "links",
    },
  ],
  requirement: [
    TITLE,
    { key: "description", label: "Как должно работать", type: "markdown" },
    { key: "criteria", label: "Как проверить", type: "markdown" },
    {
      key: "status",
      label: "Состояние",
      type: "select",
      options: ["proposed", "accepted", "implemented", "retired"],
    },
  ],
  knowledge: [
    TITLE,
    {
      key: "category",
      label: "Вид знания",
      type: "select",
      options: ["decision", "architecture", "runbook", "constraint"],
    },
    { key: "body", label: "Содержание", type: "markdown" },
    { key: "rationale", label: "Почему принято такое решение", type: "markdown" },
    { key: "url", label: "Документ или ссылка", section: "details" },
    {
      key: "status",
      label: "Актуальность",
      type: "select",
      options: ["active", "superseded"],
      section: "details",
    },
    {
      key: "supersededById",
      label: "Заменено документом",
      type: "reference",
      referenceKind: "knowledge",
      section: "links",
    },
  ],
  task: [
    TASK,
    {
      key: "type",
      label: "Вид работы",
      type: "select",
      options: ["task", "feature", "bug", "research", "debt"],
    },
    { key: "stageId", label: "Этап плана", type: "reference", referenceKind: "stage" },
    {
      key: "boundaries",
      label: "Границы поручения",
      type: "markdown",
      description: "Область кода, входные данные и ограничения исполнителя.",
    },
    { key: "acceptanceCriteria", label: "Критерии приёмки", type: "markdown" },
    { key: "expectedBehavior", label: "Ожидаемое поведение", type: "markdown", bugOnly: true },
    { key: "actualBehavior", label: "Что происходит", type: "markdown", bugOnly: true },
    { key: "reproduction", label: "Как воспроизвести", type: "markdown", bugOnly: true },
    {
      key: "severity",
      label: "Серьёзность последствий",
      type: "select",
      options: ["low", "medium", "high", "critical"],
      bugOnly: true,
    },
    { key: "affectedVersion", label: "Затронутая версия", bugOnly: true },
    { key: "environment", label: "Окружение", bugOnly: true },
    { key: "workaround", label: "Обходное решение", type: "markdown", bugOnly: true },
    {
      key: "requirementIds",
      label: "Требования",
      type: "multi",
      referenceKind: "requirement",
      section: "links",
    },
    {
      key: "knowledgeIds",
      label: "Знания для исполнителя",
      type: "multi",
      referenceKind: "knowledge",
      section: "links",
    },
  ],
  run: [
    TASK,
    { key: "agent", label: "Исполнитель", required: true },
    {
      key: "status",
      label: "Состояние попытки",
      type: "select",
      options: ["running", "succeeded", "failed", "cancelled", "unknown"],
    },
    {
      key: "source",
      label: "Источник состояния",
      type: "select",
      options: ["manual", "agent", "runtime"],
    },
    { key: "result", label: "Результат работы", type: "markdown" },
    { key: "resultCommit", label: "Коммит с результатом" },
    { key: "integrated", label: "Результат интегрирован в общую версию", type: "boolean" },
    { key: "sessionId", label: "ID сессии", section: "details" },
    { key: "branch", label: "Ветка", section: "details" },
    { key: "worktree", label: "Рабочая копия", section: "details" },
    { key: "baseCommit", label: "Исходный коммит", section: "details" },
    { key: "reason", label: "Причина завершения", type: "markdown", section: "details" },
    { key: "limitations", label: "Ограничения результата", type: "markdown", section: "details" },
    {
      key: "parentRunId",
      label: "Родительское исполнение",
      type: "reference",
      referenceKind: "run",
      section: "links",
    },
  ],
  check: [
    TITLE,
    { ...TASK, required: false },
    { key: "status", label: "Результат", type: "select", options: ["pending", "passed", "failed"] },
    EVIDENCE,
    { key: "details", label: "Что проверено и что обнаружено", type: "markdown" },
    COMMIT,
    { key: "command", label: "Команда или сценарий", type: "markdown", section: "details" },
    { key: "environment", label: "Окружение", section: "details" },
    {
      key: "source",
      label: "Источник",
      type: "select",
      options: ["manual", "agent", "ci"],
      section: "details",
    },
    RUN,
    { key: "stageId", label: "Этап", type: "reference", referenceKind: "stage", section: "links" },
    {
      key: "releaseId",
      label: "Релиз",
      type: "reference",
      referenceKind: "release",
      section: "links",
    },
    {
      key: "requirementId",
      label: "Требование",
      type: "reference",
      referenceKind: "requirement",
      section: "links",
    },
  ],
  review: [
    TASK,
    { key: "status", label: "Решение", type: "select", options: ["accepted", "changes_requested"] },
    { key: "conclusion", label: "Заключение оркестратора", type: "markdown", required: true },
    { key: "checkIds", label: "Подтверждающие проверки", type: "multi", referenceKind: "check" },
    COMMIT,
    RUN,
  ],
  question: [
    TITLE,
    { key: "body", label: "Контекст вопроса", type: "markdown" },
    { key: "assignee", label: "Кому адресован" },
    { key: "status", label: "Состояние", type: "select", options: ["open", "answered", "closed"] },
    { key: "answer", label: "Ответ или принятое решение", type: "markdown" },
    { ...TASK, required: false, section: "links" },
    { key: "planId", label: "План", type: "reference", referenceKind: "plan", section: "links" },
  ],
  release: [
    TITLE,
    { key: "versionName", label: "Версия", required: true },
    { key: "notes", label: "Что получает пользователь", type: "markdown" },
    {
      key: "status",
      label: "Состояние релиза",
      type: "select",
      options: ["planned", "ready", "released", "rolled_back"],
    },
    { key: "taskIds", label: "Состав релиза", type: "tasks" },
    COMMIT,
    { key: "limitations", label: "Известные ограничения", type: "markdown", section: "details" },
    { key: "rollback", label: "Как откатить", type: "markdown", section: "details" },
  ],
  deployment: [
    {
      key: "releaseId",
      label: "Релиз",
      type: "reference",
      referenceKind: "release",
      required: true,
    },
    {
      key: "environment",
      label: "Окружение",
      description: "Например, staging или production.",
      required: true,
    },
    {
      key: "status",
      label: "Состояние установки",
      type: "select",
      options: ["installed", "verified", "failed", "rolled_back"],
    },
    EVIDENCE,
    { key: "details", label: "Примечания к установке", type: "markdown" },
  ],
  checkpoint: [
    TITLE,
    { key: "summary", label: "Что уже сделано", type: "markdown" },
    { key: "remaining", label: "Что осталось и что мешает", type: "markdown" },
    {
      key: "nextStep",
      label: "С какого действия продолжить",
      type: "markdown",
      description: "Конкретное действие, с которого следующий оркестратор начнёт работу.",
    },
    { key: "branch", label: "Ветка", section: "details" },
    COMMIT,
    { key: "worktree", label: "Рабочая копия", section: "details" },
    { key: "environment", label: "Окружение", section: "details" },
    { key: "planId", label: "План", type: "reference", referenceKind: "plan", section: "links" },
    { key: "taskIds", label: "Незавершённая работа", type: "tasks", section: "links" },
    { key: "evidenceIds", label: "Подтверждения", type: "multi", section: "links" },
  ],
};
