/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  AddLogForProjectOkEnum,
  AddLogForProjectParams,
  AddLogRequest,
  ApiFailure,
  LogRecord,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Атомарно добавить отчёт
 *
 * @tags logs
 * @name AddLogForProject
 * @summary Атомарно добавить отчёт
 * @request POST:/api/v1/projects/{project}/tasks/{id}/logs
 */
export const addLogForProject = (
  http: ApiRequestClient,
  { id, project }: AddLogForProjectParams,
  data: AddLogRequest,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: AddLogForProjectOkEnum;
      data: LogRecord;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/tasks/${id}/logs`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
