/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  AddCommentOkEnum,
  AddCommentParams,
  AddCommentRequest,
  ApiFailure,
  CommentRecord,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Атомарно добавить комментарий
 *
 * @tags comments
 * @name AddComment
 * @summary Атомарно добавить комментарий
 * @request POST:/api/v1/tasks/{id}/comments
 */
export const addComment = (
  http: ApiRequestClient,
  { id }: AddCommentParams,
  data: AddCommentRequest,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: AddCommentOkEnum;
      data: CommentRecord;
    },
    ApiFailure
  >({
    path: `/api/v1/tasks/${id}/comments`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
