/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  ChangeDependencyForProjectOkEnum,
  ChangeDependencyForProjectParams,
  ChangeDependencyRequest,
  TaskCard,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * No description
 *
 * @tags project
 * @name ChangeDependencyForProject
 * @summary Атомарно добавить или удалить зависимость
 * @request POST:/api/v1/projects/{project}/tasks/{id}/dependencies
 */
export const changeDependencyForProject = (
  http: ApiRequestClient,
  { id, project }: ChangeDependencyForProjectParams,
  data: ChangeDependencyRequest,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: ChangeDependencyForProjectOkEnum;
      data: TaskCard;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/tasks/${id}/dependencies`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
