/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  ChangePlanTasks,
  ChangePlanTasksOkEnum,
  ChangePlanTasksParams,
  PlanningSaved,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Включить или исключить задачи этапа; незатронутые включения сохраняются
 *
 * @tags plans
 * @name ChangePlanTasks
 * @summary Включить или исключить задачи этапа; незатронутые включения сохраняются
 * @request POST:/api/v1/plans/{reference}/tasks
 */
export const changePlanTasks = (
  http: ApiRequestClient,
  { reference }: ChangePlanTasksParams,
  data: ChangePlanTasks,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: ChangePlanTasksOkEnum;
      data: PlanningSaved;
    },
    ApiFailure
  >({
    path: `/api/v1/plans/${reference}/tasks`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
