/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  ChangePlanStage,
  ChangePlanStageOkEnum,
  ChangePlanStageParams,
  PlanningSaved,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Создать, изменить, удалить пустой этап или переместить его относительно полного списка
 *
 * @tags plans
 * @name ChangePlanStage
 * @summary Создать, изменить, удалить пустой этап или переместить его относительно полного списка
 * @request POST:/api/v1/plans/{reference}/stages
 */
export const changePlanStage = (
  http: ApiRequestClient,
  { reference }: ChangePlanStageParams,
  data: ChangePlanStage,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: ChangePlanStageOkEnum;
      data: PlanningSaved;
    },
    ApiFailure
  >({
    path: `/api/v1/plans/${reference}/stages`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
