/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  ChangePlanTasks,
  ChangePlanTasksForProjectOkEnum,
  ChangePlanTasksForProjectParams,
  PlanningSaved,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Включить или исключить задачи этапа; незатронутые включения сохраняются
 *
 * @tags plans
 * @name ChangePlanTasksForProject
 * @summary Включить или исключить задачи этапа; незатронутые включения сохраняются
 * @request POST:/api/v1/projects/{project}/plans/{reference}/tasks
 */
export const changePlanTasksForProject = (
  http: ApiRequestClient,
  { reference, project }: ChangePlanTasksForProjectParams,
  data: ChangePlanTasks,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: ChangePlanTasksForProjectOkEnum;
      data: PlanningSaved;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/plans/${reference}/tasks`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
