/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  ChangePlanStage,
  ChangePlanStageForProjectOkEnum,
  ChangePlanStageForProjectParams,
  PlanningSaved,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Создать, изменить, удалить пустой этап или переместить его относительно полного списка
 *
 * @tags plans
 * @name ChangePlanStageForProject
 * @summary Создать, изменить, удалить пустой этап или переместить его относительно полного списка
 * @request POST:/api/v1/projects/{project}/plans/{reference}/stages
 */
export const changePlanStageForProject = (
  http: ApiRequestClient,
  { reference, project }: ChangePlanStageForProjectParams,
  data: ChangePlanStage,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: ChangePlanStageForProjectOkEnum;
      data: PlanningSaved;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/plans/${reference}/stages`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
