/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  ChangeDependencyOkEnum,
  ChangeDependencyParams,
  ChangeDependencyRequest,
  TaskCard,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Атомарно добавить или удалить зависимость
 *
 * @tags project
 * @name ChangeDependency
 * @summary Атомарно добавить или удалить зависимость
 * @request POST:/api/v1/tasks/{id}/dependencies
 */
export const changeDependency = (
  http: ApiRequestClient,
  { id }: ChangeDependencyParams,
  data: ChangeDependencyRequest,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: ChangeDependencyOkEnum;
      data: TaskCard;
    },
    ApiFailure
  >({
    path: `/api/v1/tasks/${id}/dependencies`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
