/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  ClaimTaskOkEnum,
  ClaimTaskParams,
  ClaimTaskRequest,
  TaskCard,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * No description
 *
 * @tags tasks
 * @name ClaimTask
 * @summary Назначить готовую задачу на автора запроса
 * @request POST:/api/v1/tasks/{id}/claim
 */
export const claimTask = (
  http: ApiRequestClient,
  { id }: ClaimTaskParams,
  data: ClaimTaskRequest,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: ClaimTaskOkEnum;
      data: TaskCard;
    },
    ApiFailure
  >({
    path: `/api/v1/tasks/${id}/claim`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
