/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  ClaimTaskForProjectOkEnum,
  ClaimTaskForProjectParams,
  ClaimTaskRequest,
  TaskCard,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Назначить готовую задачу на автора запроса
 *
 * @tags tasks
 * @name ClaimTaskForProject
 * @summary Назначить готовую задачу на автора запроса
 * @request POST:/api/v1/projects/{project}/tasks/{id}/claim
 */
export const claimTaskForProject = (
  http: ApiRequestClient,
  { id, project }: ClaimTaskForProjectParams,
  data: ClaimTaskRequest,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: ClaimTaskForProjectOkEnum;
      data: TaskCard;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/tasks/${id}/claim`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
