/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  CreateTaskForProjectOkEnum,
  CreateTaskForProjectParams,
  CreateTaskRequest,
  TaskCard,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * No description
 *
 * @tags tasks
 * @name CreateTaskForProject
 * @summary Создать задачу
 * @request POST:/api/v1/projects/{project}/tasks
 */
export const createTaskForProject = (
  http: ApiRequestClient,
  { project }: CreateTaskForProjectParams,
  data: CreateTaskRequest,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: CreateTaskForProjectOkEnum;
      data: TaskCard;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/tasks`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
