/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  CreateEntity,
  CreateEntityForProjectOkEnum,
  CreateEntityForProjectParams,
  EntitySaved,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Создать типизированную сущность и её обязательные связи одной предметной операцией
 *
 * @tags entities
 * @name CreateEntityForProject
 * @summary Создать типизированную сущность и её обязательные связи одной предметной операцией
 * @request POST:/api/v1/projects/{project}/entities
 */
export const createEntityForProject = (
  http: ApiRequestClient,
  { project }: CreateEntityForProjectParams,
  data: CreateEntity,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: CreateEntityForProjectOkEnum;
      data: EntitySaved;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/entities`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
