/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  DescribeEntityTypeForProjectOkEnum,
  DescribeEntityTypeForProjectParams,
  EntityTypeDetail,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Прочитать поля, схемы операций, фильтры и правила ключей вида
 *
 * @tags entities
 * @name DescribeEntityTypeForProject
 * @summary Прочитать поля, схемы операций, фильтры и правила ключей вида
 * @request GET:/api/v1/projects/{project}/entities/type
 */
export const describeEntityTypeForProject = (
  http: ApiRequestClient,
  { project, ...query }: DescribeEntityTypeForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: DescribeEntityTypeForProjectOkEnum;
      data: EntityTypeDetail;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/entities/type`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
