/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  DescribeEntityTypeOkEnum,
  DescribeEntityTypeParams,
  EntityTypeDetail,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Прочитать поля, схемы операций, фильтры и правила ключей вида
 *
 * @tags entities
 * @name DescribeEntityType
 * @summary Прочитать поля, схемы операций, фильтры и правила ключей вида
 * @request GET:/api/v1/entities/type
 */
export const describeEntityType = (
  http: ApiRequestClient,
  query: DescribeEntityTypeParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: DescribeEntityTypeOkEnum;
      data: EntityTypeDetail;
    },
    ApiFailure
  >({
    path: `/api/v1/entities/type`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
