/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetOverviewForProjectOkEnum,
  GetOverviewForProjectParams,
  OverviewData,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags project
 * @name GetOverviewForProject
 * @summary Обзор проекта или дерева из одного снимка
 * @request GET:/api/v1/projects/{project}/overview
 */
export const getOverviewForProject = (
  http: ApiRequestClient,
  { project, ...query }: GetOverviewForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetOverviewForProjectOkEnum;
      data: OverviewData;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/overview`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
