/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetScenarioProgressOkEnum,
  GetScenarioProgressParams,
  ScenarioProgress,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Прочитать готовность сценария и реализации приложений
 *
 * @tags progress
 * @name GetScenarioProgress
 * @summary Прочитать готовность сценария и реализации приложений
 * @request GET:/api/v1/progress/scenario
 */
export const getScenarioProgress = (
  http: ApiRequestClient,
  query: GetScenarioProgressParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetScenarioProgressOkEnum;
      data: ScenarioProgress;
    },
    ApiFailure
  >({
    path: `/api/v1/progress/scenario`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
