/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetPlanningCandidatesForProjectOkEnum,
  GetPlanningCandidatesForProjectParams,
  PlanningCandidatesPage,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Найти задачи для этапа с текущей принадлежностью и серверной фильтрацией доступности
 *
 * @tags plans
 * @name GetPlanningCandidatesForProject
 * @summary Найти задачи для этапа с текущей принадлежностью и серверной фильтрацией доступности
 * @request GET:/api/v1/projects/{project}/plans/task-candidates
 */
export const getPlanningCandidatesForProject = (
  http: ApiRequestClient,
  { project, ...query }: GetPlanningCandidatesForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetPlanningCandidatesForProjectOkEnum;
      data: PlanningCandidatesPage;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/plans/task-candidates`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
