/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetProductStateOkEnum,
  ProductState,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags product
 * @name GetProductState
 * @summary Согласованное состояние продукта и готовность
 * @request GET:/api/v1/product/state
 */
export const getProductState = (
  http: ApiRequestClient,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetProductStateOkEnum;
      data: ProductState;
    },
    ApiFailure
  >({
    path: `/api/v1/product/state`,
    method: "GET",
    format: "json",
    ...params,
  });
