/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetTaskListOkEnum,
  GetTaskListParams,
  TaskListData,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Краткая выборка задач для терминального списка
 *
 * @tags project
 * @name GetTaskList
 * @summary Краткая выборка задач для терминального списка
 * @request GET:/api/v1/task-list
 */
export const getTaskList = (
  http: ApiRequestClient,
  query: GetTaskListParams = {},
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetTaskListOkEnum;
      data: TaskListData;
    },
    ApiFailure
  >({
    path: `/api/v1/task-list`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
