/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetPlanningCandidatesOkEnum,
  GetPlanningCandidatesParams,
  PlanningCandidatesPage,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Найти задачи для этапа с текущей принадлежностью и серверной фильтрацией доступности
 *
 * @tags plans
 * @name GetPlanningCandidates
 * @summary Найти задачи для этапа с текущей принадлежностью и серверной фильтрацией доступности
 * @request GET:/api/v1/plans/task-candidates
 */
export const getPlanningCandidates = (
  http: ApiRequestClient,
  query: GetPlanningCandidatesParams = {},
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetPlanningCandidatesOkEnum;
      data: PlanningCandidatesPage;
    },
    ApiFailure
  >({
    path: `/api/v1/plans/task-candidates`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
