/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetReleasePlansForProjectOkEnum,
  GetReleasePlansForProjectParams,
  ReleaseComposition,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Планы состава; после выпуска читаются из неизменяемого снимка
 *
 * @tags releases
 * @name GetReleasePlansForProject
 * @summary Планы состава; после выпуска читаются из неизменяемого снимка
 * @request GET:/api/v1/projects/{project}/releases/{reference}/plans
 */
export const getReleasePlansForProject = (
  http: ApiRequestClient,
  { reference, project, ...query }: GetReleasePlansForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetReleasePlansForProjectOkEnum;
      data: ReleaseComposition;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/releases/${reference}/plans`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
