/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  ApplicationProgress,
  GetApplicationProgressOkEnum,
  GetApplicationProgressParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Прочитать заявленный состав приложения и раздельные счётчики задач его досок
 *
 * @tags progress
 * @name GetApplicationProgress
 * @summary Прочитать заявленный состав приложения и раздельные счётчики задач его досок
 * @request GET:/api/v1/progress/application
 */
export const getApplicationProgress = (
  http: ApiRequestClient,
  query: GetApplicationProgressParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetApplicationProgressOkEnum;
      data: ApplicationProgress;
    },
    ApiFailure
  >({
    path: `/api/v1/progress/application`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
