/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetTaskBriefingOkEnum,
  GetTaskBriefingParams,
  TaskBriefing,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Готовое поручение работнику с требованиями и границами
 *
 * @tags lifecycle
 * @name GetTaskBriefing
 * @summary Готовое поручение работнику с требованиями и границами
 * @request GET:/api/v1/project/tasks/{id}/briefing
 */
export const getTaskBriefing = (
  http: ApiRequestClient,
  { id }: GetTaskBriefingParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetTaskBriefingOkEnum;
      data: TaskBriefing;
    },
    ApiFailure
  >({
    path: `/api/v1/project/tasks/${id}/briefing`,
    method: "GET",
    format: "json",
    ...params,
  });
