/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  BoardResponse,
  GetBoardForProjectOkEnum,
  GetBoardForProjectParams,
  PageMeta,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags board
 * @name GetBoardForProject
 * @summary Получить страницу доски со всеми статусами
 * @request GET:/api/v1/projects/{project}/board
 */
export const getBoardForProject = (
  http: ApiRequestClient,
  { project, ...query }: GetBoardForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetBoardForProjectOkEnum;
      data: BoardResponse;
      meta: PageMeta;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/board`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
