/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetTaskDocumentForProjectOkEnum,
  GetTaskDocumentForProjectParams,
  TaskDocumentData,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Полный документ и контекст задачи одним чтением
 *
 * @tags project
 * @name GetTaskDocumentForProject
 * @summary Полный документ и контекст задачи одним чтением
 * @request GET:/api/v1/projects/{project}/tasks/{id}/document
 */
export const getTaskDocumentForProject = (
  http: ApiRequestClient,
  { id, project }: GetTaskDocumentForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetTaskDocumentForProjectOkEnum;
      data: TaskDocumentData;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/tasks/${id}/document`,
    method: "GET",
    format: "json",
    ...params,
  });
