/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetProductEntityForProjectOkEnum,
  GetProductEntityForProjectParams,
  ProductEntity,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Прочитать фичу, сценарий, приложение или реализацию по ключу либо ID
 *
 * @tags product
 * @name GetProductEntityForProject
 * @summary Прочитать фичу, сценарий, приложение или реализацию по ключу либо ID
 * @request GET:/api/v1/projects/{project}/product/entity
 */
export const getProductEntityForProject = (
  http: ApiRequestClient,
  { project, ...query }: GetProductEntityForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetProductEntityForProjectOkEnum;
      data: ProductEntity;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/product/entity`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
