/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  EntityKeySpaces,
  GetEntityKeySpacesForProjectOkEnum,
  GetEntityKeySpacesForProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Найти актуальные области нумерации и префиксы ключей выбранного вида
 *
 * @tags entities
 * @name GetEntityKeySpacesForProject
 * @summary Найти актуальные области нумерации и префиксы ключей выбранного вида
 * @request GET:/api/v1/projects/{project}/entities/key-spaces
 */
export const getEntityKeySpacesForProject = (
  http: ApiRequestClient,
  { project, ...query }: GetEntityKeySpacesForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetEntityKeySpacesForProjectOkEnum;
      data: EntityKeySpaces;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/entities/key-spaces`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
