/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetPlansOkEnum,
  GetPlansParams,
  PlansPage,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Каталог планов с полным прогрессом, поиском и продолжением
 *
 * @tags plans
 * @name GetPlans
 * @summary Каталог планов с полным прогрессом, поиском и продолжением
 * @request GET:/api/v1/plans
 */
export const getPlans = (
  http: ApiRequestClient,
  query: GetPlansParams = {},
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetPlansOkEnum;
      data: PlansPage;
    },
    ApiFailure
  >({
    path: `/api/v1/plans`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
