/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  BoardTaskView,
  GetBoardTaskOkEnum,
  GetBoardTaskParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags kanban
 * @name GetBoardTask
 * @summary Полная задача с Markdown и вычисляемыми блокерами
 * @request GET:/api/v1/board-tasks/{reference}
 */
export const getBoardTask = (
  http: ApiRequestClient,
  { reference }: GetBoardTaskParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetBoardTaskOkEnum;
      data: BoardTaskView;
    },
    ApiFailure
  >({
    path: `/api/v1/board-tasks/${reference}`,
    method: "GET",
    format: "json",
    ...params,
  });
