/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetProductEntitiesOkEnum,
  GetProductEntitiesParams,
  ProductEntities,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags product
 * @name GetProductEntities
 * @summary Найти продуктовые цели без загрузки Markdown; до 100 записей и продолжение
 * @request GET:/api/v1/product/entities
 */
export const getProductEntities = (
  http: ApiRequestClient,
  query: GetProductEntitiesParams = {},
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetProductEntitiesOkEnum;
      data: ProductEntities;
    },
    ApiFailure
  >({
    path: `/api/v1/product/entities`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
