/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetPlanForProjectOkEnum,
  GetPlanForProjectParams,
  PlanSummary,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Содержание плана и полные показатели состава
 *
 * @tags plans
 * @name GetPlanForProject
 * @summary Содержание плана и полные показатели состава
 * @request GET:/api/v1/projects/{project}/plans/{reference}
 */
export const getPlanForProject = (
  http: ApiRequestClient,
  { reference, project }: GetPlanForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetPlanForProjectOkEnum;
      data: PlanSummary;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/plans/${reference}`,
    method: "GET",
    format: "json",
    ...params,
  });
