/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetProjectsOkEnum,
  ServerContextResponse,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Проекты сервера
 *
 * @tags projects
 * @name GetProjects
 * @summary Проекты сервера
 * @request GET:/api/v1/projects
 */
export const getProjects = (
  http: ApiRequestClient,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetProjectsOkEnum;
      data: ServerContextResponse;
    },
    ApiFailure
  >({
    path: `/api/v1/projects`,
    method: "GET",
    format: "json",
    ...params,
  });
