/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  CheckpointChanges,
  GetCheckpointChangesForProjectOkEnum,
  GetCheckpointChangesForProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Изменения после контрольной точки
 *
 * @tags lifecycle
 * @name GetCheckpointChangesForProject
 * @summary Изменения после контрольной точки
 * @request GET:/api/v1/projects/{project}/project/checkpoints/{recordId}/changes
 */
export const getCheckpointChangesForProject = (
  http: ApiRequestClient,
  { recordId, project }: GetCheckpointChangesForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetCheckpointChangesForProjectOkEnum;
      data: CheckpointChanges;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/project/checkpoints/${recordId}/changes`,
    method: "GET",
    format: "json",
    ...params,
  });
