/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  BoardTaskView,
  GetBoardTaskForProjectOkEnum,
  GetBoardTaskForProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags kanban
 * @name GetBoardTaskForProject
 * @summary Полная задача с Markdown и вычисляемыми блокерами
 * @request GET:/api/v1/projects/{project}/board-tasks/{reference}
 */
export const getBoardTaskForProject = (
  http: ApiRequestClient,
  { reference, project }: GetBoardTaskForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetBoardTaskForProjectOkEnum;
      data: BoardTaskView;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/board-tasks/${reference}`,
    method: "GET",
    format: "json",
    ...params,
  });
