/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetTaskListForProjectOkEnum,
  GetTaskListForProjectParams,
  TaskListData,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Краткая выборка задач для терминального списка
 *
 * @tags project
 * @name GetTaskListForProject
 * @summary Краткая выборка задач для терминального списка
 * @request GET:/api/v1/projects/{project}/task-list
 */
export const getTaskListForProject = (
  http: ApiRequestClient,
  { project, ...query }: GetTaskListForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetTaskListForProjectOkEnum;
      data: TaskListData;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/task-list`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
