/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  BoardsPage,
  GetBoardsOkEnum,
  GetBoardsParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Каталог досок проекта с продолжением и проверкой версии
 *
 * @tags boards
 * @name GetBoards
 * @summary Каталог досок проекта с продолжением и проверкой версии
 * @request GET:/api/v1/boards
 */
export const getBoards = (
  http: ApiRequestClient,
  query: GetBoardsParams = {},
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetBoardsOkEnum;
      data: BoardsPage;
    },
    ApiFailure
  >({
    path: `/api/v1/boards`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
