/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetScenarioProgressForProjectOkEnum,
  GetScenarioProgressForProjectParams,
  ScenarioProgress,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Прочитать готовность сценария и реализации приложений
 *
 * @tags progress
 * @name GetScenarioProgressForProject
 * @summary Прочитать готовность сценария и реализации приложений
 * @request GET:/api/v1/projects/{project}/progress/scenario
 */
export const getScenarioProgressForProject = (
  http: ApiRequestClient,
  { project, ...query }: GetScenarioProgressForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetScenarioProgressForProjectOkEnum;
      data: ScenarioProgress;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/progress/scenario`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
