/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetProjectStateForProjectOkEnum,
  GetProjectStateForProjectParams,
  ProjectState,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags lifecycle
 * @name GetProjectStateForProject
 * @summary Паспорт, планы и фактическое состояние выбранного проекта
 * @request GET:/api/v1/projects/{project}/project/state
 */
export const getProjectStateForProject = (
  http: ApiRequestClient,
  { project }: GetProjectStateForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetProjectStateForProjectOkEnum;
      data: ProjectState;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/project/state`,
    method: "GET",
    format: "json",
    ...params,
  });
