/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetTaskHistoryForProjectOkEnum,
  GetTaskHistoryForProjectParams,
  TaskActivityPage,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Хронология сохранённых действий с фильтрами и курсором
 *
 * @tags kanban
 * @name GetTaskHistoryForProject
 * @summary Хронология сохранённых действий с фильтрами и курсором
 * @request GET:/api/v1/projects/{project}/board-tasks/{reference}/history
 */
export const getTaskHistoryForProject = (
  http: ApiRequestClient,
  { reference, project, ...query }: GetTaskHistoryForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetTaskHistoryForProjectOkEnum;
      data: TaskActivityPage;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/board-tasks/${reference}/history`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
