/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetTaskLinksOkEnum,
  GetTaskLinksParams,
  TaskLinksData,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags project
 * @name GetTaskLinks
 * @summary Связи и блокеры задачи
 * @request GET:/api/v1/tasks/{id}/links
 */
export const getTaskLinks = (
  http: ApiRequestClient,
  { id }: GetTaskLinksParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetTaskLinksOkEnum;
      data: TaskLinksData;
    },
    ApiFailure
  >({
    path: `/api/v1/tasks/${id}/links`,
    method: "GET",
    format: "json",
    ...params,
  });
