/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetPlanOkEnum,
  GetPlanParams,
  PlanSummary,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Содержание плана и полные показатели состава
 *
 * @tags plans
 * @name GetPlan
 * @summary Содержание плана и полные показатели состава
 * @request GET:/api/v1/plans/{reference}
 */
export const getPlan = (
  http: ApiRequestClient,
  { reference }: GetPlanParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetPlanOkEnum;
      data: PlanSummary;
    },
    ApiFailure
  >({
    path: `/api/v1/plans/${reference}`,
    method: "GET",
    format: "json",
    ...params,
  });
