/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetTaskDocumentOkEnum,
  GetTaskDocumentParams,
  TaskDocumentData,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags project
 * @name GetTaskDocument
 * @summary Полный документ и контекст задачи одним чтением
 * @request GET:/api/v1/tasks/{id}/document
 */
export const getTaskDocument = (
  http: ApiRequestClient,
  { id }: GetTaskDocumentParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetTaskDocumentOkEnum;
      data: TaskDocumentData;
    },
    ApiFailure
  >({
    path: `/api/v1/tasks/${id}/document`,
    method: "GET",
    format: "json",
    ...params,
  });
