/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetGraphHistoryOkEnum,
  GetGraphHistoryParams,
  GraphHistory,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags graph
 * @name GetGraphHistory
 * @summary История явно установленных отношений, включая отозванные
 * @request GET:/api/v1/graph/history
 */
export const getGraphHistory = (
  http: ApiRequestClient,
  query: GetGraphHistoryParams = {},
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetGraphHistoryOkEnum;
      data: GraphHistory;
    },
    ApiFailure
  >({
    path: `/api/v1/graph/history`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
