/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetTaskHistoryEventOkEnum,
  GetTaskHistoryEventParams,
  TaskHistoryEvent,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Полные значения до и после сохранённого изменения
 *
 * @tags kanban
 * @name GetTaskHistoryEvent
 * @summary Полные значения до и после сохранённого изменения
 * @request GET:/api/v1/board-tasks/{reference}/history/{entryId}
 */
export const getTaskHistoryEvent = (
  http: ApiRequestClient,
  { reference, entryId }: GetTaskHistoryEventParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetTaskHistoryEventOkEnum;
      data: TaskHistoryEvent;
    },
    ApiFailure
  >({
    path: `/api/v1/board-tasks/${reference}/history/${entryId}`,
    method: "GET",
    format: "json",
    ...params,
  });
