/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetProductEntityOkEnum,
  GetProductEntityParams,
  ProductEntity,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags product
 * @name GetProductEntity
 * @summary Прочитать фичу, сценарий, приложение или реализацию по ключу либо ID
 * @request GET:/api/v1/product/entity
 */
export const getProductEntity = (
  http: ApiRequestClient,
  query: GetProductEntityParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetProductEntityOkEnum;
      data: ProductEntity;
    },
    ApiFailure
  >({
    path: `/api/v1/product/entity`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
