/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  BoardInfo,
  GetBoardBySlugOkEnum,
  GetBoardBySlugParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags boards
 * @name GetBoardBySlug
 * @summary Прочитать доску по slug; неизвестный адрес возвращает 404
 * @request GET:/api/v1/boards/{slug}
 */
export const getBoardBySlug = (
  http: ApiRequestClient,
  { slug }: GetBoardBySlugParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetBoardBySlugOkEnum;
      data: BoardInfo;
    },
    ApiFailure
  >({
    path: `/api/v1/boards/${slug}`,
    method: "GET",
    format: "json",
    ...params,
  });
