/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetReleasesOkEnum,
  GetReleasesParams,
  ReleasesPage,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Каталог самостоятельных релизов с готовностью и продолжением
 *
 * @tags releases
 * @name GetReleases
 * @summary Каталог самостоятельных релизов с готовностью и продолжением
 * @request GET:/api/v1/releases
 */
export const getReleases = (
  http: ApiRequestClient,
  query: GetReleasesParams = {},
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetReleasesOkEnum;
      data: ReleasesPage;
    },
    ApiFailure
  >({
    path: `/api/v1/releases`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
