/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetPlanStagesForProjectOkEnum,
  GetPlanStagesForProjectParams,
  StagesPage,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Этапы плана в предметном порядке с полным прогрессом
 *
 * @tags plans
 * @name GetPlanStagesForProject
 * @summary Этапы плана в предметном порядке с полным прогрессом
 * @request GET:/api/v1/projects/{project}/plans/{reference}/stages
 */
export const getPlanStagesForProject = (
  http: ApiRequestClient,
  { reference, project, ...query }: GetPlanStagesForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetPlanStagesForProjectOkEnum;
      data: StagesPage;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/plans/${reference}/stages`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
