/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  FullContext,
  GetFullContextForProjectOkEnum,
  GetFullContextForProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Получить все узлы и рёбра достижимой компоненты одним вызовом; превышение бюджета возвращает ошибку
 *
 * @tags graph
 * @name GetFullContextForProject
 * @summary Получить все узлы и рёбра достижимой компоненты одним вызовом; превышение бюджета возвращает ошибку
 * @request GET:/api/v1/projects/{project}/graph/context
 */
export const getFullContextForProject = (
  http: ApiRequestClient,
  { project, ...query }: GetFullContextForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetFullContextForProjectOkEnum;
      data: FullContext;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/graph/context`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
