/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetWorkPlanProgressOkEnum,
  GetWorkPlanProgressParams,
  WorkPlanProgress,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Прочитать выполнение плана, этапы, препятствия и условия переходов
 *
 * @tags progress
 * @name GetWorkPlanProgress
 * @summary Прочитать выполнение плана, этапы, препятствия и условия переходов
 * @request GET:/api/v1/progress/work-plan
 */
export const getWorkPlanProgress = (
  http: ApiRequestClient,
  query: GetWorkPlanProgressParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetWorkPlanProgressOkEnum;
      data: WorkPlanProgress;
    },
    ApiFailure
  >({
    path: `/api/v1/progress/work-plan`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
