/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetProjectContextOkEnum,
  ProjectContext,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags lifecycle
 * @name GetProjectContext
 * @summary Компактный контекст для оркестратора
 * @request GET:/api/v1/project/context
 */
export const getProjectContext = (
  http: ApiRequestClient,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetProjectContextOkEnum;
      data: ProjectContext;
    },
    ApiFailure
  >({
    path: `/api/v1/project/context`,
    method: "GET",
    format: "json",
    ...params,
  });
