/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetPlansForProjectOkEnum,
  GetPlansForProjectParams,
  PlansPage,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Каталог планов с полным прогрессом, поиском и продолжением
 *
 * @tags plans
 * @name GetPlansForProject
 * @summary Каталог планов с полным прогрессом, поиском и продолжением
 * @request GET:/api/v1/projects/{project}/plans
 */
export const getPlansForProject = (
  http: ApiRequestClient,
  { project, ...query }: GetPlansForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetPlansForProjectOkEnum;
      data: PlansPage;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/plans`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
