/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetLogForProjectOkEnum,
  GetLogForProjectParams,
  LogRecord,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags logs
 * @name GetLogForProject
 * @summary Прочитать отчёт целиком
 * @request GET:/api/v1/projects/{project}/tasks/{id}/logs/{logId}
 */
export const getLogForProject = (
  http: ApiRequestClient,
  { id, logId, project }: GetLogForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetLogForProjectOkEnum;
      data: LogRecord;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/tasks/${id}/logs/${logId}`,
    method: "GET",
    format: "json",
    ...params,
  });
