/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetPlanStageTasksOkEnum,
  GetPlanStageTasksParams,
  PlanningTasksPage,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Страница актуальных задач этапа; описание задачи читается адресно
 *
 * @tags plans
 * @name GetPlanStageTasks
 * @summary Страница актуальных задач этапа; описание задачи читается адресно
 * @request GET:/api/v1/plans/{reference}/stages/{stage}/tasks
 */
export const getPlanStageTasks = (
  http: ApiRequestClient,
  { stage, reference, ...query }: GetPlanStageTasksParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetPlanStageTasksOkEnum;
      data: PlanningTasksPage;
    },
    ApiFailure
  >({
    path: `/api/v1/plans/${reference}/stages/${stage}/tasks`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
