/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  BoardTasksPage,
  GetBoardTasksOkEnum,
  GetBoardTasksParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags kanban
 * @name GetBoardTasks
 * @summary Задачи досок проекта с поиском, блокерами и постраничным продолжением
 * @request GET:/api/v1/board-tasks
 */
export const getBoardTasks = (
  http: ApiRequestClient,
  query: GetBoardTasksParams = {},
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetBoardTasksOkEnum;
      data: BoardTasksPage;
    },
    ApiFailure
  >({
    path: `/api/v1/board-tasks`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
