/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  EntityHistory,
  GetEntityHistoryForProjectOkEnum,
  GetEntityHistoryForProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Прочитать сохранённые события ревизий сущности по ключу или ID
 *
 * @tags entities
 * @name GetEntityHistoryForProject
 * @summary Прочитать сохранённые события ревизий сущности по ключу или ID
 * @request GET:/api/v1/projects/{project}/entities/history
 */
export const getEntityHistoryForProject = (
  http: ApiRequestClient,
  { project, ...query }: GetEntityHistoryForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetEntityHistoryForProjectOkEnum;
      data: EntityHistory;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/entities/history`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
