/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetReleasesForProjectOkEnum,
  GetReleasesForProjectParams,
  ReleasesPage,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Каталог самостоятельных релизов с готовностью и продолжением
 *
 * @tags releases
 * @name GetReleasesForProject
 * @summary Каталог самостоятельных релизов с готовностью и продолжением
 * @request GET:/api/v1/projects/{project}/releases
 */
export const getReleasesForProject = (
  http: ApiRequestClient,
  { project, ...query }: GetReleasesForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetReleasesForProjectOkEnum;
      data: ReleasesPage;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/releases`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
