/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  CommentRecord,
  GetCommentForProjectOkEnum,
  GetCommentForProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Прочитать комментарий целиком
 *
 * @tags comments
 * @name GetCommentForProject
 * @summary Прочитать комментарий целиком
 * @request GET:/api/v1/projects/{project}/tasks/{id}/comments/{commentId}
 */
export const getCommentForProject = (
  http: ApiRequestClient,
  { id, commentId, project }: GetCommentForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetCommentForProjectOkEnum;
      data: CommentRecord;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/tasks/${id}/comments/${commentId}`,
    method: "GET",
    format: "json",
    ...params,
  });
