/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetProductProgressOkEnum,
  GetProductProgressParams,
  ProductProgress,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Прочитать прогресс продукта и страницу его фич
 *
 * @tags progress
 * @name GetProductProgress
 * @summary Прочитать прогресс продукта и страницу его фич
 * @request GET:/api/v1/progress/product
 */
export const getProductProgress = (
  http: ApiRequestClient,
  query: GetProductProgressParams = {},
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetProductProgressOkEnum;
      data: ProductProgress;
    },
    ApiFailure
  >({
    path: `/api/v1/progress/product`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
