/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetProductContextForProjectOkEnum,
  GetProductContextForProjectParams,
  ProductContext,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags product
 * @name GetProductContextForProject
 * @summary Связанный продуктовый контекст
 * @request GET:/api/v1/projects/{project}/product/context
 */
export const getProductContextForProject = (
  http: ApiRequestClient,
  { project, ...query }: GetProductContextForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetProductContextForProjectOkEnum;
      data: ProductContext;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/product/context`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
