/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetProductEntitiesForProjectOkEnum,
  GetProductEntitiesForProjectParams,
  ProductEntities,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags product
 * @name GetProductEntitiesForProject
 * @summary Найти продуктовые цели без загрузки Markdown; до 100 записей и продолжение
 * @request GET:/api/v1/projects/{project}/product/entities
 */
export const getProductEntitiesForProject = (
  http: ApiRequestClient,
  { project, ...query }: GetProductEntitiesForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetProductEntitiesForProjectOkEnum;
      data: ProductEntities;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/product/entities`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
