/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetTaskTreeForProjectOkEnum,
  GetTaskTreeForProjectParams,
  TaskTreeData,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags project
 * @name GetTaskTreeForProject
 * @summary Дерево подзадач из одного снимка
 * @request GET:/api/v1/projects/{project}/tasks/{id}/tree
 */
export const getTaskTreeForProject = (
  http: ApiRequestClient,
  { id, project, ...query }: GetTaskTreeForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetTaskTreeForProjectOkEnum;
      data: TaskTreeData;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/tasks/${id}/tree`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
