/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetProductRecordsForProjectOkEnum,
  GetProductRecordsForProjectParams,
  ProductList,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags product
 * @name GetProductRecordsForProject
 * @summary Поиск и чтение записей продукта
 * @request GET:/api/v1/projects/{project}/product/records
 */
export const getProductRecordsForProject = (
  http: ApiRequestClient,
  { project, ...query }: GetProductRecordsForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetProductRecordsForProjectOkEnum;
      data: ProductList;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/product/records`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
