/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetTaskMarkdownForProjectOkEnum,
  GetTaskMarkdownForProjectParams,
  TaskMarkdownData,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Текст задачи без загрузки истории и графа
 *
 * @tags project
 * @name GetTaskMarkdownForProject
 * @summary Текст задачи без загрузки истории и графа
 * @request GET:/api/v1/projects/{project}/tasks/{id}/markdown
 */
export const getTaskMarkdownForProject = (
  http: ApiRequestClient,
  { id, project, ...query }: GetTaskMarkdownForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetTaskMarkdownForProjectOkEnum;
      data: TaskMarkdownData;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/tasks/${id}/markdown`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
