/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  BoardInfo,
  GetBoardBySlugForProjectOkEnum,
  GetBoardBySlugForProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Прочитать доску по slug; неизвестный адрес возвращает 404
 *
 * @tags boards
 * @name GetBoardBySlugForProject
 * @summary Прочитать доску по slug; неизвестный адрес возвращает 404
 * @request GET:/api/v1/projects/{project}/boards/{slug}
 */
export const getBoardBySlugForProject = (
  http: ApiRequestClient,
  { slug, project }: GetBoardBySlugForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetBoardBySlugForProjectOkEnum;
      data: BoardInfo;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/boards/${slug}`,
    method: "GET",
    format: "json",
    ...params,
  });
