/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetProductRecordsOkEnum,
  GetProductRecordsParams,
  ProductList,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags product
 * @name GetProductRecords
 * @summary Поиск и чтение записей продукта
 * @request GET:/api/v1/product/records
 */
export const getProductRecords = (
  http: ApiRequestClient,
  query: GetProductRecordsParams = {},
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetProductRecordsOkEnum;
      data: ProductList;
    },
    ApiFailure
  >({
    path: `/api/v1/product/records`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
