/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetTaskLinksForProjectOkEnum,
  GetTaskLinksForProjectParams,
  TaskLinksData,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Связи и блокеры задачи
 *
 * @tags project
 * @name GetTaskLinksForProject
 * @summary Связи и блокеры задачи
 * @request GET:/api/v1/projects/{project}/tasks/{id}/links
 */
export const getTaskLinksForProject = (
  http: ApiRequestClient,
  { id, project }: GetTaskLinksForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetTaskLinksForProjectOkEnum;
      data: TaskLinksData;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/tasks/${id}/links`,
    method: "GET",
    format: "json",
    ...params,
  });
