/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetPlanStagesOkEnum,
  GetPlanStagesParams,
  StagesPage,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Этапы плана в предметном порядке с полным прогрессом
 *
 * @tags plans
 * @name GetPlanStages
 * @summary Этапы плана в предметном порядке с полным прогрессом
 * @request GET:/api/v1/plans/{reference}/stages
 */
export const getPlanStages = (
  http: ApiRequestClient,
  { reference, ...query }: GetPlanStagesParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetPlanStagesOkEnum;
      data: StagesPage;
    },
    ApiFailure
  >({
    path: `/api/v1/plans/${reference}/stages`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
