/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  FeatureProgress,
  GetFeatureProgressForProjectOkEnum,
  GetFeatureProgressForProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Прочитать готовность фичи, её сценарии и реализации
 *
 * @tags progress
 * @name GetFeatureProgressForProject
 * @summary Прочитать готовность фичи, её сценарии и реализации
 * @request GET:/api/v1/projects/{project}/progress/feature
 */
export const getFeatureProgressForProject = (
  http: ApiRequestClient,
  { project, ...query }: GetFeatureProgressForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetFeatureProgressForProjectOkEnum;
      data: FeatureProgress;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/progress/feature`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
