/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetTaskForProjectOkEnum,
  GetTaskForProjectParams,
  TaskDetailResponse,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Получить карточку, связи и блокеры
 *
 * @tags tasks
 * @name GetTaskForProject
 * @summary Получить карточку, связи и блокеры
 * @request GET:/api/v1/projects/{project}/tasks/{id}
 */
export const getTaskForProject = (
  http: ApiRequestClient,
  { id, project }: GetTaskForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetTaskForProjectOkEnum;
      data: TaskDetailResponse;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/tasks/${id}`,
    method: "GET",
    format: "json",
    ...params,
  });
