/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  ContextResponse,
  GetContextForProjectOkEnum,
  GetContextForProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags context
 * @name GetContextForProject
 * @summary Получить проект, автора и конфигурацию
 * @request GET:/api/v1/projects/{project}/context
 */
export const getContextForProject = (
  http: ApiRequestClient,
  { project }: GetContextForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetContextForProjectOkEnum;
      data: ContextResponse;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/context`,
    method: "GET",
    format: "json",
    ...params,
  });
