/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  CriteriaPage,
  GetTaskCriteriaOkEnum,
  GetTaskCriteriaParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Критерии приёмки без полного Markdown, по 20 с продолжением
 *
 * @tags kanban
 * @name GetTaskCriteria
 * @summary Критерии приёмки без полного Markdown, по 20 с продолжением
 * @request GET:/api/v1/board-tasks/{reference}/criteria
 */
export const getTaskCriteria = (
  http: ApiRequestClient,
  { reference, ...query }: GetTaskCriteriaParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetTaskCriteriaOkEnum;
      data: CriteriaPage;
    },
    ApiFailure
  >({
    path: `/api/v1/board-tasks/${reference}/criteria`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
