/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  CriterionView,
  GetTaskCriterionForProjectOkEnum,
  GetTaskCriterionForProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Полное описание критерия приёмки и ревизия задачи
 *
 * @tags kanban
 * @name GetTaskCriterionForProject
 * @summary Полное описание критерия приёмки и ревизия задачи
 * @request GET:/api/v1/projects/{project}/board-tasks/{reference}/criteria/{criterionId}
 */
export const getTaskCriterionForProject = (
  http: ApiRequestClient,
  { reference, criterionId, project }: GetTaskCriterionForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetTaskCriterionForProjectOkEnum;
      data: CriterionView;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/board-tasks/${reference}/criteria/${criterionId}`,
    method: "GET",
    format: "json",
    ...params,
  });
