/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetGroupsForProjectOkEnum,
  GetGroupsForProjectParams,
  GroupsData,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Прогресс групп проекта
 *
 * @tags project
 * @name GetGroupsForProject
 * @summary Прогресс групп проекта
 * @request GET:/api/v1/projects/{project}/groups
 */
export const getGroupsForProject = (
  http: ApiRequestClient,
  { project }: GetGroupsForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetGroupsForProjectOkEnum;
      data: GroupsData;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/groups`,
    method: "GET",
    format: "json",
    ...params,
  });
