/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  EntityDetail,
  GetEntityForProjectOkEnum,
  GetEntityForProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Прочитать все данные сущности по ключу либо постоянному ID
 *
 * @tags entities
 * @name GetEntityForProject
 * @summary Прочитать все данные сущности по ключу либо постоянному ID
 * @request GET:/api/v1/projects/{project}/entities/get
 */
export const getEntityForProject = (
  http: ApiRequestClient,
  { project, ...query }: GetEntityForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetEntityForProjectOkEnum;
      data: EntityDetail;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/entities/get`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
