/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetReleaseProgressOkEnum,
  GetReleaseProgressParams,
  ReleaseProgress,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Прочитать готовность релиза либо исторический результат его снимка
 *
 * @tags progress
 * @name GetReleaseProgress
 * @summary Прочитать готовность релиза либо исторический результат его снимка
 * @request GET:/api/v1/progress/release
 */
export const getReleaseProgress = (
  http: ApiRequestClient,
  query: GetReleaseProgressParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetReleaseProgressOkEnum;
      data: ReleaseProgress;
    },
    ApiFailure
  >({
    path: `/api/v1/progress/release`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
