/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetGroupsOkEnum,
  GroupsData,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Прогресс групп проекта
 *
 * @tags project
 * @name GetGroups
 * @summary Прогресс групп проекта
 * @request GET:/api/v1/groups
 */
export const getGroups = (http: ApiRequestClient, params: RequestParams = {}) =>
  http.request<
    {
      ok: GetGroupsOkEnum;
      data: GroupsData;
    },
    ApiFailure
  >({
    path: `/api/v1/groups`,
    method: "GET",
    format: "json",
    ...params,
  });
