/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  BoardResponse,
  GetBoardOkEnum,
  GetBoardParams,
  PageMeta,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Получить страницу доски со всеми статусами
 *
 * @tags board
 * @name GetBoard
 * @summary Получить страницу доски со всеми статусами
 * @request GET:/api/v1/board
 */
export const getBoard = (
  http: ApiRequestClient,
  query: GetBoardParams = {},
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetBoardOkEnum;
      data: BoardResponse;
      meta: PageMeta;
    },
    ApiFailure
  >({
    path: `/api/v1/board`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
