/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetImplementationProgressOkEnum,
  GetImplementationProgressParams,
  ImplementationProgress,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Прочитать прогресс реализации и её собственные задачи
 *
 * @tags progress
 * @name GetImplementationProgress
 * @summary Прочитать прогресс реализации и её собственные задачи
 * @request GET:/api/v1/progress/implementation
 */
export const getImplementationProgress = (
  http: ApiRequestClient,
  query: GetImplementationProgressParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetImplementationProgressOkEnum;
      data: ImplementationProgress;
    },
    ApiFailure
  >({
    path: `/api/v1/progress/implementation`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
