/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetReleaseSnapshotForProjectOkEnum,
  GetReleaseSnapshotForProjectParams,
  ReleaseSnapshotPage,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Страница самодостаточного снимка с полными текстами и основаниями включения
 *
 * @tags releases
 * @name GetReleaseSnapshotForProject
 * @summary Страница самодостаточного снимка с полными текстами и основаниями включения
 * @request GET:/api/v1/projects/{project}/releases/{reference}/snapshot
 */
export const getReleaseSnapshotForProject = (
  http: ApiRequestClient,
  { reference, project, ...query }: GetReleaseSnapshotForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetReleaseSnapshotForProjectOkEnum;
      data: ReleaseSnapshotPage;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/releases/${reference}/snapshot`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
