/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  EntityKeysPage,
  GetEntityKeysOkEnum,
  GetEntityKeysParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Прочитать текущий и прежние ключи сущности с продолжением
 *
 * @tags entities
 * @name GetEntityKeys
 * @summary Прочитать текущий и прежние ключи сущности с продолжением
 * @request GET:/api/v1/entities/keys
 */
export const getEntityKeys = (
  http: ApiRequestClient,
  query: GetEntityKeysParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetEntityKeysOkEnum;
      data: EntityKeysPage;
    },
    ApiFailure
  >({
    path: `/api/v1/entities/keys`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
