/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  BoardsPage,
  GetBoardsForProjectOkEnum,
  GetBoardsForProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags boards
 * @name GetBoardsForProject
 * @summary Каталог досок проекта с продолжением и проверкой версии
 * @request GET:/api/v1/projects/{project}/boards
 */
export const getBoardsForProject = (
  http: ApiRequestClient,
  { project, ...query }: GetBoardsForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetBoardsForProjectOkEnum;
      data: BoardsPage;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/boards`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
