/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  CommentRecord,
  GetCommentOkEnum,
  GetCommentParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Прочитать комментарий целиком
 *
 * @tags comments
 * @name GetComment
 * @summary Прочитать комментарий целиком
 * @request GET:/api/v1/tasks/{id}/comments/{commentId}
 */
export const getComment = (
  http: ApiRequestClient,
  { id, commentId }: GetCommentParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetCommentOkEnum;
      data: CommentRecord;
    },
    ApiFailure
  >({
    path: `/api/v1/tasks/${id}/comments/${commentId}`,
    method: "GET",
    format: "json",
    ...params,
  });
