/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetOverviewOkEnum,
  GetOverviewParams,
  OverviewData,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags project
 * @name GetOverview
 * @summary Обзор проекта или дерева из одного снимка
 * @request GET:/api/v1/overview
 */
export const getOverview = (
  http: ApiRequestClient,
  query: GetOverviewParams = {},
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetOverviewOkEnum;
      data: OverviewData;
    },
    ApiFailure
  >({
    path: `/api/v1/overview`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
