/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetTaskProgressForProjectOkEnum,
  GetTaskProgressForProjectParams,
  TaskProgress,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Прочитать фактическое выполнение задачи, критерии и обязательства
 *
 * @tags progress
 * @name GetTaskProgressForProject
 * @summary Прочитать фактическое выполнение задачи, критерии и обязательства
 * @request GET:/api/v1/projects/{project}/progress/task
 */
export const getTaskProgressForProject = (
  http: ApiRequestClient,
  { project, ...query }: GetTaskProgressForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetTaskProgressForProjectOkEnum;
      data: TaskProgress;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/progress/task`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
