/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetGraphOkEnum,
  GetGraphParams,
  GraphPage,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags graph
 * @name GetGraph
 * @summary Граф проекта или контекст сущности с путями и согласованным продолжением
 * @request GET:/api/v1/graph
 */
export const getGraph = (
  http: ApiRequestClient,
  query: GetGraphParams = {},
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetGraphOkEnum;
      data: GraphPage;
    },
    ApiFailure
  >({
    path: `/api/v1/graph`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
