/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetProjectSettingsForProjectOkEnum,
  GetProjectSettingsForProjectParams,
  ProjectSettings,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Получить имя, slug и ревизию настроек проекта
 *
 * @tags context
 * @name GetProjectSettingsForProject
 * @summary Получить имя, slug и ревизию настроек проекта
 * @request GET:/api/v1/projects/{project}/context/settings
 */
export const getProjectSettingsForProject = (
  http: ApiRequestClient,
  { project }: GetProjectSettingsForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetProjectSettingsForProjectOkEnum;
      data: ProjectSettings;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/context/settings`,
    method: "GET",
    format: "json",
    ...params,
  });
