/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetGraphForProjectOkEnum,
  GetGraphForProjectParams,
  GraphPage,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Граф проекта или контекст сущности с путями и согласованным продолжением
 *
 * @tags graph
 * @name GetGraphForProject
 * @summary Граф проекта или контекст сущности с путями и согласованным продолжением
 * @request GET:/api/v1/projects/{project}/graph
 */
export const getGraphForProject = (
  http: ApiRequestClient,
  { project, ...query }: GetGraphForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetGraphForProjectOkEnum;
      data: GraphPage;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/graph`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
