/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetReleasePlansOkEnum,
  GetReleasePlansParams,
  ReleaseComposition,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Планы состава; после выпуска читаются из неизменяемого снимка
 *
 * @tags releases
 * @name GetReleasePlans
 * @summary Планы состава; после выпуска читаются из неизменяемого снимка
 * @request GET:/api/v1/releases/{reference}/plans
 */
export const getReleasePlans = (
  http: ApiRequestClient,
  { reference, ...query }: GetReleasePlansParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetReleasePlansOkEnum;
      data: ReleaseComposition;
    },
    ApiFailure
  >({
    path: `/api/v1/releases/${reference}/plans`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
