/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  BoardTaskLinksPage,
  GetBoardTaskLinksOkEnum,
  GetBoardTaskLinksParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Прямые и обратные связи задач с состояниями и продолжением
 *
 * @tags kanban
 * @name GetBoardTaskLinks
 * @summary Прямые и обратные связи задач с состояниями и продолжением
 * @request GET:/api/v1/board-tasks/{reference}/links
 */
export const getBoardTaskLinks = (
  http: ApiRequestClient,
  { reference, ...query }: GetBoardTaskLinksParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetBoardTaskLinksOkEnum;
      data: BoardTaskLinksPage;
    },
    ApiFailure
  >({
    path: `/api/v1/board-tasks/${reference}/links`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
