/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetServerContextOkEnum,
  ServerContextResponse,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags server
 * @name GetServerContext
 * @summary Режим Relay и доступные проекты
 * @request GET:/api/v1/server
 */
export const getServerContext = (
  http: ApiRequestClient,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetServerContextOkEnum;
      data: ServerContextResponse;
    },
    ApiFailure
  >({
    path: `/api/v1/server`,
    method: "GET",
    format: "json",
    ...params,
  });
