/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetGraphHistoryForProjectOkEnum,
  GetGraphHistoryForProjectParams,
  GraphHistory,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags graph
 * @name GetGraphHistoryForProject
 * @summary История явно установленных отношений, включая отозванные
 * @request GET:/api/v1/projects/{project}/graph/history
 */
export const getGraphHistoryForProject = (
  http: ApiRequestClient,
  { project, ...query }: GetGraphHistoryForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetGraphHistoryForProjectOkEnum;
      data: GraphHistory;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/graph/history`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
