/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetProductStateForProjectOkEnum,
  GetProductStateForProjectParams,
  ProductState,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Согласованное состояние продукта и готовность
 *
 * @tags product
 * @name GetProductStateForProject
 * @summary Согласованное состояние продукта и готовность
 * @request GET:/api/v1/projects/{project}/product/state
 */
export const getProductStateForProject = (
  http: ApiRequestClient,
  { project }: GetProductStateForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetProductStateForProjectOkEnum;
      data: ProductState;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/product/state`,
    method: "GET",
    format: "json",
    ...params,
  });
