/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetProductContextOkEnum,
  GetProductContextParams,
  ProductContext,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags product
 * @name GetProductContext
 * @summary Связанный продуктовый контекст
 * @request GET:/api/v1/product/context
 */
export const getProductContext = (
  http: ApiRequestClient,
  query: GetProductContextParams = {},
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetProductContextOkEnum;
      data: ProductContext;
    },
    ApiFailure
  >({
    path: `/api/v1/product/context`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
