/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  ContextResponse,
  GetContextOkEnum,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Получить проект, автора и конфигурацию
 *
 * @tags context
 * @name GetContext
 * @summary Получить проект, автора и конфигурацию
 * @request GET:/api/v1/context
 */
export const getContext = (
  http: ApiRequestClient,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetContextOkEnum;
      data: ContextResponse;
    },
    ApiFailure
  >({
    path: `/api/v1/context`,
    method: "GET",
    format: "json",
    ...params,
  });
