/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  BoardTaskSaved,
  LinkBoardTask,
  LinkBoardTaskForProjectOkEnum,
  LinkBoardTaskForProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * No description
 *
 * @tags kanban
 * @name LinkBoardTaskForProject
 * @summary Добавить или удалить связь, зависимость либо родителя; циклы запрещены
 * @request POST:/api/v1/projects/{project}/board-tasks/{reference}/links
 */
export const linkBoardTaskForProject = (
  http: ApiRequestClient,
  { reference, project }: LinkBoardTaskForProjectParams,
  data: LinkBoardTask,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: LinkBoardTaskForProjectOkEnum;
      data: BoardTaskSaved;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/board-tasks/${reference}/links`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
