/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  EntitySaved,
  LinkEntityTask,
  LinkEntityTaskOkEnum,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Установить или снять зависимость, контекстную связь либо родительство задач по ключам или ID
 *
 * @tags entities
 * @name LinkEntityTask
 * @summary Установить или снять зависимость, контекстную связь либо родительство задач по ключам или ID
 * @request POST:/api/v1/entities/link-task
 */
export const linkEntityTask = (
  http: ApiRequestClient,
  data: LinkEntityTask,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: LinkEntityTaskOkEnum;
      data: EntitySaved;
    },
    ApiFailure
  >({
    path: `/api/v1/entities/link-task`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
