/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  EntityTypes,
  ListEntityTypesForProjectOkEnum,
  ListEntityTypesForProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Перечислить основные виды сущностей, их назначение и возможности
 *
 * @tags entities
 * @name ListEntityTypesForProject
 * @summary Перечислить основные виды сущностей, их назначение и возможности
 * @request GET:/api/v1/projects/{project}/entities/types
 */
export const listEntityTypesForProject = (
  http: ApiRequestClient,
  { project, ...query }: ListEntityTypesForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: ListEntityTypesForProjectOkEnum;
      data: EntityTypes;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/entities/types`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
