/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  BoardResponse,
  ListTasksForProjectOkEnum,
  ListTasksForProjectParams,
  PageMeta,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags tasks
 * @name ListTasksForProject
 * @summary Получить страницу задач
 * @request GET:/api/v1/projects/{project}/tasks
 */
export const listTasksForProject = (
  http: ApiRequestClient,
  { project, ...query }: ListTasksForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: ListTasksForProjectOkEnum;
      data: BoardResponse;
      meta: PageMeta;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/tasks`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
