/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  EntityTypes,
  ListEntityTypesOkEnum,
  ListEntityTypesParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Перечислить основные виды сущностей, их назначение и возможности
 *
 * @tags entities
 * @name ListEntityTypes
 * @summary Перечислить основные виды сущностей, их назначение и возможности
 * @request GET:/api/v1/entities/types
 */
export const listEntityTypes = (
  http: ApiRequestClient,
  query: ListEntityTypesParams = {},
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: ListEntityTypesOkEnum;
      data: EntityTypes;
    },
    ApiFailure
  >({
    path: `/api/v1/entities/types`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
