/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  EntitiesPage,
  ListEntitiesForProjectOkEnum,
  ListEntitiesForProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Найти сущности по виду, ключу и предметным фильтрам; до 100 карточек со снимком
 *
 * @tags entities
 * @name ListEntitiesForProject
 * @summary Найти сущности по виду, ключу и предметным фильтрам; до 100 карточек со снимком
 * @request GET:/api/v1/projects/{project}/entities
 */
export const listEntitiesForProject = (
  http: ApiRequestClient,
  { project, ...query }: ListEntitiesForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: ListEntitiesForProjectOkEnum;
      data: EntitiesPage;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/entities`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
