/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  CommentsPage,
  ListCommentsForProjectOkEnum,
  ListCommentsForProjectParams,
  PageMeta,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags comments
 * @name ListCommentsForProject
 * @summary Прочитать страницу комментариев от новых к старым
 * @request GET:/api/v1/projects/{project}/tasks/{id}/comments
 */
export const listCommentsForProject = (
  http: ApiRequestClient,
  { id, project, ...query }: ListCommentsForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: ListCommentsForProjectOkEnum;
      data: CommentsPage;
      meta: PageMeta;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/tasks/${id}/comments`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
