/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  ListLogsForProjectOkEnum,
  ListLogsForProjectParams,
  LogsPage,
  PageMeta,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags logs
 * @name ListLogsForProject
 * @summary Прочитать страницу отчётов от новых к старым
 * @request GET:/api/v1/projects/{project}/tasks/{id}/logs
 */
export const listLogsForProject = (
  http: ApiRequestClient,
  { id, project, ...query }: ListLogsForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: ListLogsForProjectOkEnum;
      data: LogsPage;
      meta: PageMeta;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/tasks/${id}/logs`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
