/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  BoardResponse,
  ListTasksOkEnum,
  ListTasksParams,
  PageMeta,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Получить страницу задач
 *
 * @tags tasks
 * @name ListTasks
 * @summary Получить страницу задач
 * @request GET:/api/v1/tasks
 */
export const listTasks = (
  http: ApiRequestClient,
  query: ListTasksParams = {},
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: ListTasksOkEnum;
      data: BoardResponse;
      meta: PageMeta;
    },
    ApiFailure
  >({
    path: `/api/v1/tasks`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
