/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  BoardTaskSaved,
  MoveBoardTask,
  MoveBoardTaskOkEnum,
  MoveBoardTaskParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Изменить колонку, порядок или доску; ID сохраняется, ключ меняется при переносе
 *
 * @tags kanban
 * @name MoveBoardTask
 * @summary Изменить колонку, порядок или доску; ID сохраняется, ключ меняется при переносе
 * @request POST:/api/v1/board-tasks/{reference}/move
 */
export const moveBoardTask = (
  http: ApiRequestClient,
  { reference }: MoveBoardTaskParams,
  data: MoveBoardTask,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: MoveBoardTaskOkEnum;
      data: BoardTaskSaved;
    },
    ApiFailure
  >({
    path: `/api/v1/board-tasks/${reference}/move`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
