/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  MoveTaskForProjectOkEnum,
  MoveTaskForProjectParams,
  MoveTaskRequest,
  TaskCard,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Атомарно изменить статус и позицию карточки
 *
 * @tags tasks
 * @name MoveTaskForProject
 * @summary Атомарно изменить статус и позицию карточки
 * @request POST:/api/v1/projects/{project}/tasks/{id}/move
 */
export const moveTaskForProject = (
  http: ApiRequestClient,
  { id, project }: MoveTaskForProjectParams,
  data: MoveTaskRequest,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: MoveTaskForProjectOkEnum;
      data: TaskCard;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/tasks/${id}/move`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
