/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  EntitySaved,
  MoveEntityTask,
  MoveEntityTaskOkEnum,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Переместить задачу; задача, доска и позиция принимают ключи или ID
 *
 * @tags entities
 * @name MoveEntityTask
 * @summary Переместить задачу; задача, доска и позиция принимают ключи или ID
 * @request POST:/api/v1/entities/move-task
 */
export const moveEntityTask = (
  http: ApiRequestClient,
  data: MoveEntityTask,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: MoveEntityTaskOkEnum;
      data: EntitySaved;
    },
    ApiFailure
  >({
    path: `/api/v1/entities/move-task`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
