/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  MutateProductOkEnum,
  ProductMutation,
  ProductSaved,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * No description
 *
 * @tags product
 * @name MutateProduct
 * @summary Создать или изменить запись продукта
 * @request POST:/api/v1/product/records
 */
export const mutateProduct = (
  http: ApiRequestClient,
  data: ProductMutation,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: MutateProductOkEnum;
      data: ProductSaved;
    },
    ApiFailure
  >({
    path: `/api/v1/product/records`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
