/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  EntityDeletionPreview,
  PreviewEntityDeletionOkEnum,
  PreviewEntityDeletionParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Показать полный каскад удаления и сохраняемые сущности со снимаемыми связями; максимум 1000 записей
 *
 * @tags entities
 * @name PreviewEntityDeletion
 * @summary Показать полный каскад удаления и сохраняемые сущности со снимаемыми связями; максимум 1000 записей
 * @request GET:/api/v1/entities/deletion-preview
 */
export const previewEntityDeletion = (
  http: ApiRequestClient,
  query: PreviewEntityDeletionParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: PreviewEntityDeletionOkEnum;
      data: EntityDeletionPreview;
    },
    ApiFailure
  >({
    path: `/api/v1/entities/deletion-preview`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
