/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  PreviewReleaseOkEnum,
  ReleaseComposition,
  ReleasePreview,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Прочитать готовность выбранных планов без записи релиза
 *
 * @tags releases
 * @name PreviewRelease
 * @summary Прочитать готовность выбранных планов без записи релиза
 * @request POST:/api/v1/releases/preview
 */
export const previewRelease = (
  http: ApiRequestClient,
  data: ReleasePreview,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: PreviewReleaseOkEnum;
      data: ReleaseComposition;
    },
    ApiFailure
  >({
    path: `/api/v1/releases/preview`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
