/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  RegisterProjectOkEnum,
  RegisterProjectParams,
  RegisterProjectRequest,
  ServerContextResponse,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * No description
 *
 * @tags projects
 * @name RegisterProject
 * @summary Зарегистрировать проект workspace
 * @request PUT:/api/v1/projects/{project}
 */
export const registerProject = (
  http: ApiRequestClient,
  { project }: RegisterProjectParams,
  data: RegisterProjectRequest,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: RegisterProjectOkEnum;
      data: ServerContextResponse;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}`,
    method: "PUT",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
