/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  ReleaseTaskOkEnum,
  ReleaseTaskParams,
  ReleaseTaskRequest,
  TaskCard,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * No description
 *
 * @tags tasks
 * @name ReleaseTask
 * @summary Снять назначение, сохранив статус
 * @request POST:/api/v1/tasks/{id}/release
 */
export const releaseTask = (
  http: ApiRequestClient,
  { id }: ReleaseTaskParams,
  data: ReleaseTaskRequest,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: ReleaseTaskOkEnum;
      data: TaskCard;
    },
    ApiFailure
  >({
    path: `/api/v1/tasks/${id}/release`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
