/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  ReleaseTaskForProjectOkEnum,
  ReleaseTaskForProjectParams,
  ReleaseTaskRequest,
  TaskCard,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Снять назначение, сохранив статус
 *
 * @tags tasks
 * @name ReleaseTaskForProject
 * @summary Снять назначение, сохранив статус
 * @request POST:/api/v1/projects/{project}/tasks/{id}/release
 */
export const releaseTaskForProject = (
  http: ApiRequestClient,
  { id, project }: ReleaseTaskForProjectParams,
  data: ReleaseTaskRequest,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: ReleaseTaskForProjectOkEnum;
      data: TaskCard;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/tasks/${id}/release`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
