/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  EntitySaved,
  RenameEntity,
  RenameEntityKeyOkEnum,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Изменить читаемый ключ, сохранив ID, связи и прежние алиасы
 *
 * @tags entities
 * @name RenameEntityKey
 * @summary Изменить читаемый ключ, сохранив ID, связи и прежние алиасы
 * @request POST:/api/v1/entities/rename
 */
export const renameEntityKey = (
  http: ApiRequestClient,
  data: RenameEntity,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: RenameEntityKeyOkEnum;
      data: EntitySaved;
    },
    ApiFailure
  >({
    path: `/api/v1/entities/rename`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
