/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  EntitySummary,
  ResolveEntityForProjectOkEnum,
  ResolveEntityForProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Разрешить текущий ключ, алиас или ID в постоянный адрес и краткую карточку
 *
 * @tags entities
 * @name ResolveEntityForProject
 * @summary Разрешить текущий ключ, алиас или ID в постоянный адрес и краткую карточку
 * @request GET:/api/v1/projects/{project}/entities/resolve
 */
export const resolveEntityForProject = (
  http: ApiRequestClient,
  { project, ...query }: ResolveEntityForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: ResolveEntityForProjectOkEnum;
      data: EntitySummary;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/entities/resolve`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
