/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  EntitySummary,
  ResolveEntityOkEnum,
  ResolveEntityParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Разрешить текущий ключ, алиас или ID в постоянный адрес и краткую карточку
 *
 * @tags entities
 * @name ResolveEntity
 * @summary Разрешить текущий ключ, алиас или ID в постоянный адрес и краткую карточку
 * @request GET:/api/v1/entities/resolve
 */
export const resolveEntity = (
  http: ApiRequestClient,
  query: ResolveEntityParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: ResolveEntityOkEnum;
      data: EntitySummary;
    },
    ApiFailure
  >({
    path: `/api/v1/entities/resolve`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
