/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  ProjectRecord,
  SaveProjectRecord,
  SaveProjectRecordForProjectOkEnum,
  SaveProjectRecordForProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * No description
 *
 * @tags lifecycle
 * @name SaveProjectRecordForProject
 * @summary Создать или обновить проектный документ с проверкой ревизии
 * @request POST:/api/v1/projects/{project}/project/records
 */
export const saveProjectRecordForProject = (
  http: ApiRequestClient,
  { project }: SaveProjectRecordForProjectParams,
  data: SaveProjectRecord,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: SaveProjectRecordForProjectOkEnum;
      data: ProjectRecord;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/project/records`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
