/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  ProjectRecord,
  SaveProjectRecord,
  SaveProjectRecordOkEnum,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Создать или обновить проектный документ с проверкой ревизии
 *
 * @tags lifecycle
 * @name SaveProjectRecord
 * @summary Создать или обновить проектный документ с проверкой ревизии
 * @request POST:/api/v1/project/records
 */
export const saveProjectRecord = (
  http: ApiRequestClient,
  data: SaveProjectRecord,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: SaveProjectRecordOkEnum;
      data: ProjectRecord;
    },
    ApiFailure
  >({
    path: `/api/v1/project/records`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
