/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  ProjectSettings,
  SaveProjectSettings,
  SaveProjectSettingsOkEnum,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * No description
 *
 * @tags context
 * @name SaveProjectSettings
 * @summary Сохранить имя и slug проекта; повтор тех же значений идемпотентен
 * @request PUT:/api/v1/context/settings
 */
export const saveProjectSettings = (
  http: ApiRequestClient,
  data: SaveProjectSettings,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: SaveProjectSettingsOkEnum;
      data: ProjectSettings;
    },
    ApiFailure
  >({
    path: `/api/v1/context/settings`,
    method: "PUT",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
