/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  PlanningSaved,
  TransitionPlan,
  TransitionPlanForProjectOkEnum,
  TransitionPlanForProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Начать, завершить с итогом или отменить план; готовность повторно проверяется Core
 *
 * @tags plans
 * @name TransitionPlanForProject
 * @summary Начать, завершить с итогом или отменить план; готовность повторно проверяется Core
 * @request POST:/api/v1/projects/{project}/plans/{reference}/transition
 */
export const transitionPlanForProject = (
  http: ApiRequestClient,
  { reference, project }: TransitionPlanForProjectParams,
  data: TransitionPlan,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: TransitionPlanForProjectOkEnum;
      data: PlanningSaved;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/plans/${reference}/transition`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
