/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  PlanningSaved,
  TransferPlanTask,
  TransferPlanTaskOkEnum,
  TransferPlanTaskParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Перенести задачу с причиной и проверкой ревизий обоих планов
 *
 * @tags plans
 * @name TransferPlanTask
 * @summary Перенести задачу с причиной и проверкой ревизий обоих планов
 * @request POST:/api/v1/plans/{reference}/transfer
 */
export const transferPlanTask = (
  http: ApiRequestClient,
  { reference }: TransferPlanTaskParams,
  data: TransferPlanTask,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: TransferPlanTaskOkEnum;
      data: PlanningSaved;
    },
    ApiFailure
  >({
    path: `/api/v1/plans/${reference}/transfer`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
