/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  PlanningSaved,
  ReleaseAction,
  TransitionReleaseForProjectOkEnum,
  TransitionReleaseForProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Перепланировать, отменить либо явно выпустить релиз с проверкой всего состава
 *
 * @tags releases
 * @name TransitionReleaseForProject
 * @summary Перепланировать, отменить либо явно выпустить релиз с проверкой всего состава
 * @request POST:/api/v1/projects/{project}/releases/{reference}/transition
 */
export const transitionReleaseForProject = (
  http: ApiRequestClient,
  { reference, project }: TransitionReleaseForProjectParams,
  data: ReleaseAction,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: TransitionReleaseForProjectOkEnum;
      data: PlanningSaved;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/releases/${reference}/transition`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
