/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  ServerContextResponse,
  UnregisterProjectOkEnum,
  UnregisterProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags projects
 * @name UnregisterProject
 * @summary Удалить регистрацию проекта
 * @request DELETE:/api/v1/projects/{project}
 */
export const unregisterProject = (
  http: ApiRequestClient,
  { project }: UnregisterProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: UnregisterProjectOkEnum;
      data: ServerContextResponse;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}`,
    method: "DELETE",
    format: "json",
    ...params,
  });
