/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  BoardTaskSaved,
  UpdateBoardTask,
  UpdateBoardTaskForProjectOkEnum,
  UpdateBoardTaskForProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Изменить содержание или продуктовые связи с проверкой ревизии
 *
 * @tags kanban
 * @name UpdateBoardTaskForProject
 * @summary Изменить содержание или продуктовые связи с проверкой ревизии
 * @request POST:/api/v1/projects/{project}/board-tasks/{reference}/update
 */
export const updateBoardTaskForProject = (
  http: ApiRequestClient,
  { reference, project }: UpdateBoardTaskForProjectParams,
  data: UpdateBoardTask,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: UpdateBoardTaskForProjectOkEnum;
      data: BoardTaskSaved;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/board-tasks/${reference}/update`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
