/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  TaskCard,
  UpdateTaskForProjectOkEnum,
  UpdateTaskForProjectParams,
  UpdateTaskRequest,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * No description
 *
 * @tags tasks
 * @name UpdateTaskForProject
 * @summary Изменить поля с проверкой ревизии
 * @request PATCH:/api/v1/projects/{project}/tasks/{id}
 */
export const updateTaskForProject = (
  http: ApiRequestClient,
  { id, project }: UpdateTaskForProjectParams,
  data: UpdateTaskRequest,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: UpdateTaskForProjectOkEnum;
      data: TaskCard;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/tasks/${id}`,
    method: "PATCH",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
