/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  TaskCard,
  UpdateTaskOkEnum,
  UpdateTaskParams,
  UpdateTaskRequest,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Изменить поля с проверкой ревизии
 *
 * @tags tasks
 * @name UpdateTask
 * @summary Изменить поля с проверкой ревизии
 * @request PATCH:/api/v1/tasks/{id}
 */
export const updateTask = (
  http: ApiRequestClient,
  { id }: UpdateTaskParams,
  data: UpdateTaskRequest,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: UpdateTaskOkEnum;
      data: TaskCard;
    },
    ApiFailure
  >({
    path: `/api/v1/tasks/${id}`,
    method: "PATCH",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
