/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  PlanningSaved,
  UpdatePlan,
  UpdatePlanOkEnum,
  UpdatePlanParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Изменить только заданные поля плана с проверкой ревизии
 *
 * @tags plans
 * @name UpdatePlan
 * @summary Изменить только заданные поля плана с проверкой ревизии
 * @request POST:/api/v1/plans/{reference}/update
 */
export const updatePlan = (
  http: ApiRequestClient,
  { reference }: UpdatePlanParams,
  data: UpdatePlan,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: UpdatePlanOkEnum;
      data: PlanningSaved;
    },
    ApiFailure
  >({
    path: `/api/v1/plans/${reference}/update`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
