/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  PlanningSaved,
  UpdateRelease,
  UpdateReleaseForProjectOkEnum,
  UpdateReleaseForProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Изменить реквизиты, состав и выбранное состояние одной согласованной операцией
 *
 * @tags releases
 * @name UpdateReleaseForProject
 * @summary Изменить реквизиты, состав и выбранное состояние одной согласованной операцией
 * @request POST:/api/v1/projects/{project}/releases/{reference}/update
 */
export const updateReleaseForProject = (
  http: ApiRequestClient,
  { reference, project }: UpdateReleaseForProjectParams,
  data: UpdateRelease,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: UpdateReleaseForProjectOkEnum;
      data: PlanningSaved;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/releases/${reference}/update`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
