/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  ValidateProjectOkEnum,
  ValidationData,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Проверить продукт, доски, задачи и граф связей проекта
 *
 * @tags project
 * @name ValidateProject
 * @summary Проверить продукт, доски, задачи и граф связей проекта
 * @request GET:/api/v1/validation
 */
export const validateProject = (
  http: ApiRequestClient,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: ValidateProjectOkEnum;
      data: ValidationData;
    },
    ApiFailure
  >({
    path: `/api/v1/validation`,
    method: "GET",
    format: "json",
    ...params,
  });
