/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  ValidateProjectForProjectOkEnum,
  ValidateProjectForProjectParams,
  ValidationData,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * No description
 *
 * @tags project
 * @name ValidateProjectForProject
 * @summary Проверить документы и граф проекта
 * @request GET:/api/v1/projects/{project}/validation
 */
export const validateProjectForProject = (
  http: ApiRequestClient,
  { project }: ValidateProjectForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: ValidateProjectForProjectOkEnum;
      data: ValidationData;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/validation`,
    method: "GET",
    format: "json",
    ...params,
  });
