/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  WatchEventsForProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description SSE-уведомления connected, changed и workspace-error; heartbeat каждые 15 секунд поддерживает поток при простое и не требует перечитывать REST. Поле event соответствует type, JSON в data — полю data схемы ServerEvent. После подключения и восстановления соединения перечитайте REST. Доставка может объединять и повторять изменения; воспроизведение по Last-Event-ID не поддерживается.
 *
 * @tags events
 * @name WatchEventsForProject
 * @summary Подписаться на изменения проекта
 * @request GET:/api/v1/projects/{project}/events
 */
export const watchEventsForProject = (
  http: ApiRequestClient,
  { project }: WatchEventsForProjectParams,
  params: RequestParams = {},
) =>
  http.request<string, ApiFailure>({
    path: `/api/v1/projects/${project}/events`,
    method: "GET",
    format: "text",
    ...params,
  });
