/**
 * Стабильные коды ожидаемых ошибок Authentication.
 */
export const AUTHENTICATION_ERROR_CODE = {
  INVALID_CREDENTIALS: 'AUTHENTICATION_INVALID_CREDENTIALS',
  TEMPORARILY_UNAVAILABLE: 'AUTHENTICATION_TEMPORARILY_UNAVAILABLE'
} as const
