import { z } from "zod";
import {
  entityPageQuerySchema,
  entityTypeQuerySchema,
  entityTypesSchema,
  entityTypeDetailSchema,
  entitiesQuerySchema,
  entitiesPageSchema,
  entityGetQuerySchema,
  entitySummarySchema,
  entityDetailSchema,
  entityKeysQuerySchema,
  entityKeysPageSchema,
  entityKeySpacesQuerySchema,
  entityKeySpacesSchema,
  entityCreateSchema,
  entityUpdateSchema,
  entityRenameSchema,
  entityMoveTaskSchema,
  entityLinkTaskSchema,
  entitySavedSchema,
  entityHistorySchema,
  entityDeletionQuerySchema,
  entityDeletionPreviewSchema,
  deleteEntitySchema,
  entityDeletedSchema,
} from "@relay/contracts/entities";
import {
  graphPageSchema,
  graphQuerySchema,
  graphMutationSchema,
  graphSavedSchema,
  graphHistorySchema,
  graphHistoryQuerySchema,
  fullContextSchema,
  fullContextQuerySchema,
} from "@relay/core/domain/entity-graph";
import {
  productEntitiesQuerySchema,
  productEntitiesSchema,
  productEntitySchema,
  productEntityQuerySchema,
  updateImplementationSchema,
} from "@relay/core/domain/product-implementation";
import {
  boardTaskViewSchema,
  criteriaPageSchema,
  criteriaQuerySchema,
  criterionViewSchema,
  changeCriterionSchema,
  taskActivityQuerySchema,
  taskActivityPageSchema,
  taskHistoryEventSchema,
  taskCommentSavedSchema,
  publishTaskCommentSchema,
  boardTaskSavedSchema,
  boardTasksPageSchema,
  boardTaskLinksPageSchema,
  boardTasksQuerySchema,
  createBoardTaskSchema,
  updateBoardTaskSchema,
  moveBoardTaskSchema,
  linkBoardTaskSchema,
} from "@relay/core/domain/board-task";
import {
  productStateSchema,
  productMutationSchema,
  productSavedSchema,
  productContextSchema,
  productContextQuerySchema,
  productOverviewSchema,
  productListSchema,
  productListQuerySchema,
} from "@relay/core/domain/product";
import { configSchema } from "@relay/core/domain/config";
import {
  projectSettingsSchema,
  saveProjectSettingsSchema,
} from "@relay/core/domain/project-settings";
import { boardViewSchema, boardsQuerySchema, boardsPageSchema } from "@relay/core/domain/board";
import { API_CONTRACT_VERSION } from "@relay/contracts";

const contextSchema = z.strictObject({
  capabilities: z.array(z.string()).optional(),
  project: z.string(),
  projectId: z.string().describe("Стабильный идентификатор пути конфигурации проекта"),
  configPath: z.string(),
  storagePath: z.string(),
  actor: z.string().describe("Автор изменений, заданный при запуске сервера"),
  config: configSchema,
});
const serverEventSchema = z.discriminatedUnion("type", [
  z.strictObject({ type: z.literal("connected"), data: z.strictObject({ projectId: z.string() }) }),
  z.strictObject({ type: z.literal("heartbeat"), data: z.strictObject({ timestamp: z.string() }) }),
  z.strictObject({
    type: z.literal("changed"),
    data: z.strictObject({ source: z.enum(["api", "storage"]), version: z.string().optional() }),
  }),
  z.strictObject({
    type: z.literal("workspace-error"),
    data: z.strictObject({ code: z.string(), message: z.string() }),
  }),
]);

export const schemas = {
  EntityDeletionQuery: entityDeletionQuerySchema,
  EntityDeletionPreview: entityDeletionPreviewSchema,
  DeleteEntity: deleteEntitySchema,
  EntityDeleted: entityDeletedSchema,
  TaskActivityQuery: taskActivityQuerySchema,
  TaskActivityPage: taskActivityPageSchema,
  TaskHistoryEvent: taskHistoryEventSchema,
  TaskCommentSaved: taskCommentSavedSchema,
  PublishTaskComment: publishTaskCommentSchema,
  EntityPageQuery: entityPageQuerySchema,
  EntityTypeQuery: entityTypeQuerySchema,
  EntityTypes: entityTypesSchema,
  EntityTypeDetail: entityTypeDetailSchema,
  EntitiesQuery: entitiesQuerySchema,
  EntitiesPage: entitiesPageSchema,
  EntityGetQuery: entityGetQuerySchema,
  EntitySummary: entitySummarySchema,
  EntityDetail: entityDetailSchema,
  EntityKeysQuery: entityKeysQuerySchema,
  EntityKeysPage: entityKeysPageSchema,
  EntityKeySpacesQuery: entityKeySpacesQuerySchema,
  EntityKeySpaces: entityKeySpacesSchema,
  EntityHistory: entityHistorySchema,
  CreateEntity: entityCreateSchema,
  UpdateEntity: entityUpdateSchema,
  RenameEntity: entityRenameSchema,
  MoveEntityTask: entityMoveTaskSchema,
  LinkEntityTask: entityLinkTaskSchema,
  EntitySaved: entitySavedSchema,
  GraphPage: graphPageSchema,
  GraphQuery: graphQuerySchema,
  GraphMutation: graphMutationSchema,
  GraphSaved: graphSavedSchema,
  GraphHistory: graphHistorySchema,
  GraphHistoryQuery: graphHistoryQuerySchema,
  FullContext: fullContextSchema,
  FullContextQuery: fullContextQuerySchema,
  ProjectSettings: projectSettingsSchema,
  SaveProjectSettings: saveProjectSettingsSchema,
  BoardTaskView: boardTaskViewSchema,
  CriteriaPage: criteriaPageSchema,
  CriteriaQuery: criteriaQuerySchema,
  CriterionView: criterionViewSchema,
  ChangeCriterion: changeCriterionSchema,
  BoardTaskSaved: boardTaskSavedSchema,
  BoardTasksPage: boardTasksPageSchema,
  BoardTaskLinksPage: boardTaskLinksPageSchema,
  BoardTasksQuery: boardTasksQuerySchema,
  CreateBoardTask: createBoardTaskSchema,
  UpdateBoardTask: updateBoardTaskSchema,
  MoveBoardTask: moveBoardTaskSchema,
  LinkBoardTask: linkBoardTaskSchema,
  ServerContextResponse: z.strictObject({
    mode: z.enum(["local", "workspace"]),
    configPath: z.string(),
    defaultProject: z.string().nullable(),
    projects: z.array(
      z.strictObject({
        key: z.string(),
        id: z.string(),
        name: z.string(),
        slug: z
          .string()
          .optional()
          .describe("Человекочитаемый адрес проекта; постоянный id не меняется"),
        configPath: z.string(),
        available: z.boolean(),
        error: z.string().optional(),
      }),
    ),
  }),
  RegisterProjectRequest: z.strictObject({
    path: z.string().optional(),
    config: z.string().optional(),
    replace: z.boolean().optional(),
  }),
  ProductState: productStateSchema,
  ProductEntities: productEntitiesSchema,
  ProductEntitiesQuery: productEntitiesQuerySchema,
  ProductEntity: productEntitySchema,
  ProductEntityQuery: productEntityQuerySchema,
  UpdateImplementation: updateImplementationSchema,
  ProductMutation: productMutationSchema,
  ProductSaved: productSavedSchema,
  ProductContext: productContextSchema,
  ProductContextQuery: productContextQuerySchema,
  ProductOverview: productOverviewSchema,
  ProductList: productListSchema,
  ProductListQuery: productListQuerySchema,
  ValidationData: z.object({
    valid: z.boolean(),
    entities: z.number(),
    tasks: z.number(),
    boards: z.number(),
  }),
  ServerEvent: serverEventSchema,
  HealthResponse: z.strictObject({
    status: z.literal("ok"),
    stage: z.enum(["scaffold", "ready"]),
    contractVersion: z.literal(API_CONTRACT_VERSION),
  }),
  ContextResponse: contextSchema,
  BoardInfo: boardViewSchema,
  BoardsQuery: boardsQuerySchema,
  BoardsPage: boardsPageSchema,
  PageMeta: z.strictObject({
    hasMore: z.boolean(),
    nextCursor: z.string().nullable(),
    truncated: z.boolean().optional(),
  }),
  ApiFailure: z.strictObject({
    ok: z.literal(false),
    error: z.strictObject({
      code: z.string(),
      message: z.string(),
      details: z.unknown().optional(),
      exitCode: z.number().int().min(1).max(255).optional(),
    }),
  }),
};

export type SchemaName = keyof typeof schemas;
