/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

export interface ServerContextResponse {
  mode: ServerContextResponseModeEnum;
  configPath: string;
  defaultProject: string | null;
  projects: {
    key: string;
    id: string;
    name: string;
    configPath: string;
    available: boolean;
    error?: string;
  }[];
}

export interface RegisterProjectRequest {
  path?: string;
  config?: string;
  replace?: boolean;
}

export interface TaskListQuery {
  status?: string;
  group?: string;
  assignee?: string;
  parent?: string | number;
  tag?: string;
  /** @maxLength 4096 */
  search?: string;
  ready?: boolean;
  all?: boolean;
  sort?: TaskListQuerySortEnum;
}

export interface TaskListData {
  items: {
    /**
     * @exclusiveMin 0
     * @max 9007199254740991
     */
    id: number;
    /** @minLength 1 */
    title: string;
    /** @minLength 1 */
    status: string;
    group: string | null;
    /** @maxItems 100 */
    tags: string[];
    parentId: number | null;
    assignee: string | null;
    /**
     * @exclusiveMin 0
     * @max 9007199254740991
     */
    revision: number;
    /**
     * @format date-time
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
     */
    createdAt: string;
    /**
     * @format date-time
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
     */
    updatedAt: string;
    blockedBy: number[];
  }[];
  readyIds: number[];
}

export interface TaskDocumentData {
  task: {
    /** @minLength 1 */
    title: string;
    description: string[];
    /** @minLength 1 */
    status: string;
    group: string | null;
    /** @maxItems 100 */
    tags: string[];
    parentId: number | null;
    /** @maxItems 1000 */
    dependsOn: number[];
    assignee: string | null;
    /**
     * @maxLength 2048
     * @pattern ^-?\d+\/[1-9]\d*$
     */
    rank?: string;
    summary: string[];
    version: 2;
    /**
     * @exclusiveMin 0
     * @max 9007199254740991
     */
    id: number;
    /**
     * @format date-time
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
     */
    createdAt: string;
    /**
     * @format date-time
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
     */
    updatedAt: string;
    /** @maxLength 128 */
    createdBy: string;
    /** @maxLength 128 */
    updatedBy: string;
    /**
     * @exclusiveMin 0
     * @max 9007199254740991
     */
    revision: number;
    comments: Partial<
      Record<
        string,
        {
          version: 1;
          /** @pattern ^cmt_[a-f0-9]{32}$ */
          id: string;
          /**
           * @exclusiveMin 0
           * @max 9007199254740991
           */
          taskId: number;
          /** @maxLength 128 */
          actor: string;
          /**
           * @format date-time
           * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
           */
          createdAt: string;
          body: string[];
        }
      >
    >;
    logs: Partial<
      Record<
        string,
        {
          version: 1;
          /** @pattern ^log_[a-f0-9]{32}$ */
          id: string;
          /**
           * @exclusiveMin 0
           * @max 9007199254740991
           */
          taskId: number;
          /** @maxLength 128 */
          actor: string;
          /**
           * @format date-time
           * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
           */
          createdAt: string;
          kind: TaskDocumentDataKindEnum;
          /** @minLength 0 */
          title: string;
          summary: string[];
          sessionId: string | null;
          body: string[];
        }
      >
    >;
  };
  related: {
    /**
     * @exclusiveMin 0
     * @max 9007199254740991
     */
    id: number;
    /** @minLength 1 */
    title: string;
    /** @minLength 1 */
    status: string;
  }[];
  blockedBy: number[];
  ready: boolean;
}

export interface TaskMarkdownQuery {
  field: TaskMarkdownQueryFieldEnum;
}

export interface TaskMarkdownData {
  /**
   * @exclusiveMin 0
   * @max 9007199254740991
   */
  id: number;
  lines: string[];
}

export interface TaskLinksData {
  task: {
    /**
     * @exclusiveMin 0
     * @max 9007199254740991
     */
    id: number;
    /** @minLength 1 */
    title: string;
    /** @minLength 1 */
    status: string;
  };
  id: number;
  parent: {
    /**
     * @exclusiveMin 0
     * @max 9007199254740991
     */
    id: number;
    /** @minLength 1 */
    title: string;
    /** @minLength 1 */
    status: string;
  } | null;
  children: {
    /**
     * @exclusiveMin 0
     * @max 9007199254740991
     */
    id: number;
    /** @minLength 1 */
    title: string;
    /** @minLength 1 */
    status: string;
  }[];
  dependsOn: {
    /**
     * @exclusiveMin 0
     * @max 9007199254740991
     */
    id: number;
    /** @minLength 1 */
    title: string;
    /** @minLength 1 */
    status: string;
  }[];
  blocks: {
    /**
     * @exclusiveMin 0
     * @max 9007199254740991
     */
    id: number;
    /** @minLength 1 */
    title: string;
    /** @minLength 1 */
    status: string;
  }[];
  blockedBy: number[];
}

export interface TaskTreeData {
  items: {
    /**
     * @exclusiveMin 0
     * @max 9007199254740991
     */
    id: number;
    /** @minLength 1 */
    title: string;
    /** @minLength 1 */
    status: string;
    group: string | null;
    /** @maxItems 100 */
    tags: string[];
    parentId: number | null;
    assignee: string | null;
    /**
     * @exclusiveMin 0
     * @max 9007199254740991
     */
    revision: number;
    /**
     * @format date-time
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
     */
    createdAt: string;
    /**
     * @format date-time
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
     */
    updatedAt: string;
    depth: number;
  }[];
  truncated: boolean;
  blockedCounts: Partial<Record<string, number>>;
}

export interface TreeQuery {
  /**
   * @min 0
   * @max 100
   * @default 3
   */
  depth: number;
}

export type GroupsData = {
  name: string;
  total: number;
  completed: number;
  terminal: number;
}[];

export interface OverviewQuery {
  /**
   * @min 1
   * @max 100
   * @default 5
   */
  limit: number;
  /**
   * @maxItems 100
   * @minItems 1
   */
  reviewStatuses?: string[];
  /**
   * @exclusiveMin 0
   * @max 9007199254740991
   */
  rootId?: number;
}

export interface OverviewData {
  root: {
    id: number;
    title: string;
    status: string;
    group: string | null;
    assignee: string | null;
    parentId: number | null;
    revision: number;
    blockedByCount: number;
  } | null;
  version: string;
  limit: number;
  counts: {
    total: number;
    open: number;
    completed: number;
    terminal: number;
    byStatus: Partial<Record<string, number>>;
  };
  leafCounts: {
    total: number;
    open: number;
    completed: number;
    terminal: number;
    byStatus: Partial<Record<string, number>>;
  };
  reviewStatuses: string[];
  progress: {
    total: number;
    items: {
      id: number;
      title: string;
      status: string;
      group: string | null;
      assignee: string | null;
      parentId: number | null;
      revision: number;
      blockedByCount: number;
      children: {
        total: number;
        open: number;
        completed: number;
        terminal: number;
        byStatus: Partial<Record<string, number>>;
      };
    }[];
  };
  ready: {
    total: number;
    items: {
      id: number;
      title: string;
      status: string;
      group: string | null;
      assignee: string | null;
      parentId: number | null;
      revision: number;
      blockedByCount: number;
    }[];
  };
  review: {
    total: number;
    items: {
      id: number;
      title: string;
      status: string;
      group: string | null;
      assignee: string | null;
      parentId: number | null;
      revision: number;
      blockedByCount: number;
      blockedCount: number;
      unblocksCount: number;
      readyAfterCompletionCount: number;
    }[];
  };
  blockers: {
    total: number;
    items: {
      id: number;
      title: string;
      status: string;
      group: string | null;
      assignee: string | null;
      parentId: number | null;
      revision: number;
      blockedByCount: number;
      blockedCount: number;
      unblocksCount: number;
      readyAfterCompletionCount: number;
      outsideScope: boolean;
    }[];
  };
}

export interface ChangeDependencyRequest {
  /**
   * @exclusiveMin 0
   * @max 9007199254740991
   */
  dependencyId: number;
  action: ChangeDependencyRequestActionEnum;
  /** @maxLength 128 */
  actor?: string;
  /**
   * Ожидаемая revision документа; при несовпадении HTTP 409 REVISION_CONFLICT
   * @min 1
   * @max 9007199254740991
   */
  ifRevision?: number;
}

export interface ValidationData {
  valid: boolean;
  tasks: number;
  comments: number;
  logs: number;
}

export type ServerEvent =
  | {
      type: "connected";
      data: {
        projectId: string;
      };
    }
  | {
      type: "heartbeat";
      data: {
        timestamp: string;
      };
    }
  | {
      type: "changed";
      data: {
        source: ServerEventSourceEnum;
        taskIds?: number[];
        version?: string;
      };
    }
  | {
      type: "workspace-error";
      data: {
        code: string;
        message: string;
      };
    };

export interface HealthResponse {
  status: "ok";
  stage: HealthResponseStageEnum;
  contractVersion: 1;
}

export interface ContextResponse {
  capabilities?: string[];
  project: string;
  /** Стабильный идентификатор пути конфигурации проекта */
  projectId: string;
  configPath: string;
  storagePath: string;
  /** Автор изменений, заданный при запуске сервера */
  actor: string;
  config: {
    version: 1;
    /** @default "local" */
    mode: "local";
    /**
     * @format uuid
     * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
     */
    projectId?: string;
    /** @minLength 1 */
    storageDir: string;
    /** @minLength 1 */
    defaultStatus: string;
    /** @minItems 1 */
    readyStatuses: string[];
    statuses: Partial<
      Record<
        string,
        {
          /** @default false */
          terminal: boolean;
          /** @default false */
          satisfiesDependencies: boolean;
          color?: ContextResponseColorEnum;
        }
      >
    >;
    mcp?: {
      /**
       * @min 0
       * @max 65535
       * @default 3010
       */
      port: number;
    };
    /** @default {"port":3000} */
    server: {
      /**
       * @min 0
       * @max 65535
       * @default 3000
       */
      port: number;
      /** @format uri */
      url?: string;
    };
    /** @default {"format":"text","defaultLimit":20,"maxBytes":16384} */
    output: {
      /** @default "text" */
      format: ContextResponseFormatEnum;
      /**
       * @min 1
       * @max 100
       * @default 20
       */
      defaultLimit: number;
      /**
       * @min 1024
       * @max 16777216
       * @default 16384
       */
      maxBytes: number;
    };
  };
}

export interface CreateTaskRequest {
  /**
   * Непустая строка, до 1024 байт UTF-8
   * @minLength 1
   * @maxLength 1024
   */
  title: string;
  /** Markdown: массив строк, до 256 КиБ UTF-8 суммарно */
  description?: string[];
  /**
   * Ключ из context.config.statuses; изменение статуса помещает задачу в конец целевой колонки
   * @minLength 1
   */
  status?: string;
  /** Группа или null для снятия группы */
  group?: string | null;
  /** @maxItems 100 */
  tags?: string[];
  parentId?: number | null;
  /** @maxItems 1000 */
  dependsOn?: number[];
  /** Исполнитель или null; отличается от автора изменений */
  assignee?: string | null;
  /** Markdown: массив строк, до 4096 байт UTF-8 суммарно */
  summary?: string[];
  /** @maxLength 128 */
  actor?: string;
}

export interface UpdateTaskRequest {
  patch: {
    /**
     * Непустая строка, до 1024 байт UTF-8
     * @minLength 1
     * @maxLength 1024
     */
    title?: string;
    /** Markdown: массив строк, до 256 КиБ UTF-8 суммарно */
    description?: string[];
    /**
     * Ключ из context.config.statuses; изменение статуса помещает задачу в конец целевой колонки
     * @minLength 1
     */
    status?: string;
    /** Группа или null для снятия группы */
    group?: string | null;
    /** @maxItems 100 */
    tags?: string[];
    parentId?: number | null;
    /** @maxItems 1000 */
    dependsOn?: number[];
    /** Исполнитель или null; отличается от автора изменений */
    assignee?: string | null;
    /** Markdown: массив строк, до 4096 байт UTF-8 суммарно */
    summary?: string[];
  };
  /**
   * Ожидаемая revision документа; при несовпадении HTTP 409 REVISION_CONFLICT
   * @min 1
   * @max 9007199254740991
   */
  ifRevision?: number;
  /** @maxLength 128 */
  actor?: string;
}

export interface MoveTaskRequest {
  /** @minLength 1 */
  status: string;
  /** ID карточки, перед которой вставляется задача; null — конец полной колонки */
  beforeId: number | null;
  /**
   * Ожидаемая revision документа; при несовпадении HTTP 409 REVISION_CONFLICT
   * @min 1
   * @max 9007199254740991
   */
  ifRevision: number;
  /** @maxLength 128 */
  actor?: string;
}

export interface ClaimTaskRequest {
  /**
   * Ожидаемая revision документа; при несовпадении HTTP 409 REVISION_CONFLICT
   * @min 1
   * @max 9007199254740991
   */
  ifRevision?: number;
  /** @minLength 1 */
  status?: string;
  /** @maxLength 128 */
  actor?: string;
}

export interface ReleaseTaskRequest {
  /**
   * Ожидаемая revision документа; при несовпадении HTTP 409 REVISION_CONFLICT
   * @min 1
   * @max 9007199254740991
   */
  ifRevision?: number;
  force?: boolean;
  /** @maxLength 128 */
  actor?: string;
}

export interface AddCommentRequest {
  /**
   * Непустой текст, до 65536 байт UTF-8
   * @minLength 1
   * @maxLength 65536
   */
  text: string;
  /** @maxLength 128 */
  actor?: string;
  /**
   * @minLength 1
   * @maxLength 128
   * @pattern ^[A-Za-z0-9][A-Za-z0-9._:-]*$
   */
  requestId?: string;
}

export interface AddLogRequest {
  /**
   * Непустой текст, до 262144 байт UTF-8
   * @minLength 1
   * @maxLength 262144
   */
  text: string;
  /** По умолчанию progress */
  kind?: AddLogRequestKindEnum;
  /**
   * До 1024 байт UTF-8; по умолчанию пустая строка
   * @minLength 0
   */
  title?: string;
  /** До 4096 байт UTF-8; по умолчанию пустой текст */
  summary?: string;
  /** @maxLength 128 */
  sessionId?: string;
  /** @maxLength 128 */
  actor?: string;
  /**
   * @minLength 1
   * @maxLength 128
   * @pattern ^[A-Za-z0-9][A-Za-z0-9._:-]*$
   */
  requestId?: string;
}

export interface BoardQuery {
  /** @maxLength 4096 */
  search?: string;
  /** @minLength 1 */
  status?: string;
  group?: string;
  assignee?: string;
  tag?: string;
  ready?: boolean;
  blocked?: boolean;
  unassigned?: boolean;
  ungrouped?: boolean;
  /**
   * @min 1
   * @max 500
   * @default 200
   */
  limit: number;
  /**
   * @minLength 1
   * @maxLength 4096
   */
  cursor?: string;
}

export interface CommentQuery {
  author?: string;
  /** @maxLength 4096 */
  search?: string;
  /**
   * @min 1
   * @max 100
   * @default 20
   */
  limit: number;
  /**
   * @minLength 1
   * @maxLength 4096
   */
  cursor?: string;
}

export interface LogQuery {
  author?: string;
  /** @maxLength 4096 */
  search?: string;
  /**
   * @min 1
   * @max 100
   * @default 20
   */
  limit: number;
  /**
   * @minLength 1
   * @maxLength 4096
   */
  cursor?: string;
  kind?: LogQueryKindEnum;
}

export interface TaskCard {
  /** @minLength 1 */
  title: string;
  description: string[];
  /** @minLength 1 */
  status: string;
  group: string | null;
  /** @maxItems 100 */
  tags: string[];
  parentId: number | null;
  /** @maxItems 1000 */
  dependsOn: number[];
  assignee: string | null;
  /**
   * @maxLength 2048
   * @pattern ^-?\d+\/[1-9]\d*$
   */
  rank?: string;
  summary: string[];
  version: 2;
  /**
   * @exclusiveMin 0
   * @max 9007199254740991
   */
  id: number;
  /**
   * @format date-time
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
   */
  createdAt: string;
  /**
   * @format date-time
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
   */
  updatedAt: string;
  /** @maxLength 128 */
  createdBy: string;
  /** @maxLength 128 */
  updatedBy: string;
  /**
   * @exclusiveMin 0
   * @max 9007199254740991
   */
  revision: number;
  /**
   * @min 0
   * @max 9007199254740991
   */
  commentCount: number;
  /**
   * @min 0
   * @max 9007199254740991
   */
  logCount: number;
}

export interface BoardCard {
  /** @minLength 1 */
  title: string;
  /** @minLength 1 */
  status: string;
  group: string | null;
  /** @maxItems 100 */
  tags: string[];
  parentId: number | null;
  assignee: string | null;
  /** Непрозрачное значение порядка; сортировку выполняет сервер */
  rank: string;
  /**
   * @exclusiveMin 0
   * @max 9007199254740991
   */
  id: number;
  /**
   * @format date-time
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
   */
  createdAt: string;
  /**
   * @format date-time
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
   */
  updatedAt: string;
  /**
   * @exclusiveMin 0
   * @max 9007199254740991
   */
  revision: number;
  /**
   * @min 0
   * @max 9007199254740991
   */
  commentCount: number;
  /**
   * @min 0
   * @max 9007199254740991
   */
  logCount: number;
  blockedBy: number[];
  ready: boolean;
  /**
   * @min 0
   * @max 9007199254740991
   */
  childrenCount: number;
  /**
   * @min 0
   * @max 9007199254740991
   */
  childrenCompleted: number;
}

export interface TaskDetailResponse {
  task: {
    /** @minLength 1 */
    title: string;
    description: string[];
    /** @minLength 1 */
    status: string;
    group: string | null;
    /** @maxItems 100 */
    tags: string[];
    parentId: number | null;
    /** @maxItems 1000 */
    dependsOn: number[];
    assignee: string | null;
    /**
     * @maxLength 2048
     * @pattern ^-?\d+\/[1-9]\d*$
     */
    rank?: string;
    summary: string[];
    version: 2;
    /**
     * @exclusiveMin 0
     * @max 9007199254740991
     */
    id: number;
    /**
     * @format date-time
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
     */
    createdAt: string;
    /**
     * @format date-time
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
     */
    updatedAt: string;
    /** @maxLength 128 */
    createdBy: string;
    /** @maxLength 128 */
    updatedBy: string;
    /**
     * @exclusiveMin 0
     * @max 9007199254740991
     */
    revision: number;
    /**
     * @min 0
     * @max 9007199254740991
     */
    commentCount: number;
    /**
     * @min 0
     * @max 9007199254740991
     */
    logCount: number;
  };
  blockedBy: number[];
  ready: boolean;
  parent: {
    /** @minLength 1 */
    title: string;
    /** @minLength 1 */
    status: string;
    group: string | null;
    /** @maxItems 100 */
    tags: string[];
    parentId: number | null;
    assignee: string | null;
    /** Непрозрачное значение порядка; сортировку выполняет сервер */
    rank: string;
    /**
     * @exclusiveMin 0
     * @max 9007199254740991
     */
    id: number;
    /**
     * @format date-time
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
     */
    createdAt: string;
    /**
     * @format date-time
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
     */
    updatedAt: string;
    /**
     * @exclusiveMin 0
     * @max 9007199254740991
     */
    revision: number;
    /**
     * @min 0
     * @max 9007199254740991
     */
    commentCount: number;
    /**
     * @min 0
     * @max 9007199254740991
     */
    logCount: number;
    blockedBy: number[];
    ready: boolean;
    /**
     * @min 0
     * @max 9007199254740991
     */
    childrenCount: number;
    /**
     * @min 0
     * @max 9007199254740991
     */
    childrenCompleted: number;
  } | null;
  children: {
    /** @minLength 1 */
    title: string;
    /** @minLength 1 */
    status: string;
    group: string | null;
    /** @maxItems 100 */
    tags: string[];
    parentId: number | null;
    assignee: string | null;
    /** Непрозрачное значение порядка; сортировку выполняет сервер */
    rank: string;
    /**
     * @exclusiveMin 0
     * @max 9007199254740991
     */
    id: number;
    /**
     * @format date-time
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
     */
    createdAt: string;
    /**
     * @format date-time
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
     */
    updatedAt: string;
    /**
     * @exclusiveMin 0
     * @max 9007199254740991
     */
    revision: number;
    /**
     * @min 0
     * @max 9007199254740991
     */
    commentCount: number;
    /**
     * @min 0
     * @max 9007199254740991
     */
    logCount: number;
    blockedBy: number[];
    ready: boolean;
    /**
     * @min 0
     * @max 9007199254740991
     */
    childrenCount: number;
    /**
     * @min 0
     * @max 9007199254740991
     */
    childrenCompleted: number;
  }[];
  dependencies: {
    /** @minLength 1 */
    title: string;
    /** @minLength 1 */
    status: string;
    group: string | null;
    /** @maxItems 100 */
    tags: string[];
    parentId: number | null;
    assignee: string | null;
    /** Непрозрачное значение порядка; сортировку выполняет сервер */
    rank: string;
    /**
     * @exclusiveMin 0
     * @max 9007199254740991
     */
    id: number;
    /**
     * @format date-time
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
     */
    createdAt: string;
    /**
     * @format date-time
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
     */
    updatedAt: string;
    /**
     * @exclusiveMin 0
     * @max 9007199254740991
     */
    revision: number;
    /**
     * @min 0
     * @max 9007199254740991
     */
    commentCount: number;
    /**
     * @min 0
     * @max 9007199254740991
     */
    logCount: number;
    blockedBy: number[];
    ready: boolean;
    /**
     * @min 0
     * @max 9007199254740991
     */
    childrenCount: number;
    /**
     * @min 0
     * @max 9007199254740991
     */
    childrenCompleted: number;
  }[];
  blocks: {
    /** @minLength 1 */
    title: string;
    /** @minLength 1 */
    status: string;
    group: string | null;
    /** @maxItems 100 */
    tags: string[];
    parentId: number | null;
    assignee: string | null;
    /** Непрозрачное значение порядка; сортировку выполняет сервер */
    rank: string;
    /**
     * @exclusiveMin 0
     * @max 9007199254740991
     */
    id: number;
    /**
     * @format date-time
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
     */
    createdAt: string;
    /**
     * @format date-time
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
     */
    updatedAt: string;
    /**
     * @exclusiveMin 0
     * @max 9007199254740991
     */
    revision: number;
    /**
     * @min 0
     * @max 9007199254740991
     */
    commentCount: number;
    /**
     * @min 0
     * @max 9007199254740991
     */
    logCount: number;
    blockedBy: number[];
    ready: boolean;
    /**
     * @min 0
     * @max 9007199254740991
     */
    childrenCount: number;
    /**
     * @min 0
     * @max 9007199254740991
     */
    childrenCompleted: number;
  }[];
}

export interface BoardResponse {
  context: {
    capabilities?: string[];
    project: string;
    /** Стабильный идентификатор пути конфигурации проекта */
    projectId: string;
    configPath: string;
    storagePath: string;
    /** Автор изменений, заданный при запуске сервера */
    actor: string;
    config: {
      version: 1;
      /** @default "local" */
      mode: "local";
      /**
       * @format uuid
       * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
       */
      projectId?: string;
      /** @minLength 1 */
      storageDir: string;
      /** @minLength 1 */
      defaultStatus: string;
      /** @minItems 1 */
      readyStatuses: string[];
      statuses: Partial<
        Record<
          string,
          {
            /** @default false */
            terminal: boolean;
            /** @default false */
            satisfiesDependencies: boolean;
            color?: BoardResponseColorEnum;
          }
        >
      >;
      mcp?: {
        /**
         * @min 0
         * @max 65535
         * @default 3010
         */
        port: number;
      };
      /** @default {"port":3000} */
      server: {
        /**
         * @min 0
         * @max 65535
         * @default 3000
         */
        port: number;
        /** @format uri */
        url?: string;
      };
      /** @default {"format":"text","defaultLimit":20,"maxBytes":16384} */
      output: {
        /** @default "text" */
        format: BoardResponseFormatEnum;
        /**
         * @min 1
         * @max 100
         * @default 20
         */
        defaultLimit: number;
        /**
         * @min 1024
         * @max 16777216
         * @default 16384
         */
        maxBytes: number;
      };
    };
  };
  items: {
    /** @minLength 1 */
    title: string;
    /** @minLength 1 */
    status: string;
    group: string | null;
    /** @maxItems 100 */
    tags: string[];
    parentId: number | null;
    assignee: string | null;
    /** Непрозрачное значение порядка; сортировку выполняет сервер */
    rank: string;
    /**
     * @exclusiveMin 0
     * @max 9007199254740991
     */
    id: number;
    /**
     * @format date-time
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
     */
    createdAt: string;
    /**
     * @format date-time
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
     */
    updatedAt: string;
    /**
     * @exclusiveMin 0
     * @max 9007199254740991
     */
    revision: number;
    /**
     * @min 0
     * @max 9007199254740991
     */
    commentCount: number;
    /**
     * @min 0
     * @max 9007199254740991
     */
    logCount: number;
    blockedBy: number[];
    ready: boolean;
    /**
     * @min 0
     * @max 9007199254740991
     */
    childrenCount: number;
    /**
     * @min 0
     * @max 9007199254740991
     */
    childrenCompleted: number;
  }[];
  /**
   * @min 0
   * @max 9007199254740991
   */
  total: number;
  /** Счётчики всех отфильтрованных задач до пагинации, включая пустые колонки */
  counts: Partial<Record<string, number>>;
  groups: string[];
  /** Полные размеры групп проекта независимо от фильтров и пагинации; null — без группы */
  groupCounts: {
    group: string | null;
    /**
     * @min 0
     * @max 9007199254740991
     */
    count: number;
  }[];
  assignees: string[];
  tags: string[];
  /** Версия полного снимка задач и конфигурации */
  version: string;
}

export interface CommentRecord {
  version: 1;
  /** @pattern ^cmt_[a-f0-9]{32}$ */
  id: string;
  /**
   * @exclusiveMin 0
   * @max 9007199254740991
   */
  taskId: number;
  /** @maxLength 128 */
  actor: string;
  /**
   * @format date-time
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
   */
  createdAt: string;
  body: string[];
}

export interface LogRecord {
  version: 1;
  /** @pattern ^log_[a-f0-9]{32}$ */
  id: string;
  /**
   * @exclusiveMin 0
   * @max 9007199254740991
   */
  taskId: number;
  /** @maxLength 128 */
  actor: string;
  /**
   * @format date-time
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
   */
  createdAt: string;
  kind: LogRecordKindEnum;
  /** @minLength 0 */
  title: string;
  summary: string[];
  sessionId: string | null;
  body: string[];
}

export interface CommentsPage {
  items: {
    version: 1;
    /** @pattern ^cmt_[a-f0-9]{32}$ */
    id: string;
    /**
     * @exclusiveMin 0
     * @max 9007199254740991
     */
    taskId: number;
    /** @maxLength 128 */
    actor: string;
    /**
     * @format date-time
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
     */
    createdAt: string;
    body: string[];
  }[];
}

export interface LogsPage {
  items: {
    version: 1;
    /** @pattern ^log_[a-f0-9]{32}$ */
    id: string;
    /**
     * @exclusiveMin 0
     * @max 9007199254740991
     */
    taskId: number;
    /** @maxLength 128 */
    actor: string;
    /**
     * @format date-time
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
     */
    createdAt: string;
    kind: LogsPageKindEnum;
    /** @minLength 0 */
    title: string;
    summary: string[];
    sessionId: string | null;
    body: string[];
  }[];
}

export interface PageMeta {
  hasMore: boolean;
  nextCursor: string | null;
  truncated?: boolean;
}

export interface ApiFailure {
  ok: false;
  error: {
    code: string;
    message: string;
    details?: any;
    /**
     * @min 1
     * @max 255
     */
    exitCode?: number;
  };
}

export type ServerContextResponseModeEnum = "local" | "workspace";

export type TaskListQuerySortEnum = "id" | "board";

export type TaskDocumentDataKindEnum =
  | "progress"
  | "decision"
  | "execution"
  | "error"
  | "summary";

export type TaskMarkdownQueryFieldEnum = "description" | "summary";

export type ChangeDependencyRequestActionEnum = "add" | "remove";

export type ServerEventSourceEnum = "api" | "storage";

export type HealthResponseStageEnum = "scaffold" | "ready";

export type ContextResponseColorEnum =
  | "black"
  | "red"
  | "green"
  | "yellow"
  | "blue"
  | "magenta"
  | "cyan"
  | "white"
  | "gray"
  | "none";

/** @default "text" */
export type ContextResponseFormatEnum = "json" | "text";

/** По умолчанию progress */
export type AddLogRequestKindEnum =
  | "progress"
  | "decision"
  | "execution"
  | "error"
  | "summary";

export type LogQueryKindEnum =
  | "progress"
  | "decision"
  | "execution"
  | "error"
  | "summary";

export type BoardResponseColorEnum =
  | "black"
  | "red"
  | "green"
  | "yellow"
  | "blue"
  | "magenta"
  | "cyan"
  | "white"
  | "gray"
  | "none";

/** @default "text" */
export type BoardResponseFormatEnum = "json" | "text";

export type LogRecordKindEnum =
  | "progress"
  | "decision"
  | "execution"
  | "error"
  | "summary";

export type LogsPageKindEnum =
  | "progress"
  | "decision"
  | "execution"
  | "error"
  | "summary";

export type GetHealthOkEnum = true;

export type GetServerContextOkEnum = true;

export type GetProjectsOkEnum = true;

export type RegisterProjectOkEnum = true;

export interface RegisterProjectParams {
  project: string;
}

export type UnregisterProjectOkEnum = true;

export interface UnregisterProjectParams {
  project: string;
}

export type GetContextOkEnum = true;

export type GetBoardOkEnum = true;

export interface GetBoardParams {
  /** @maxLength 4096 */
  search?: string;
  /** @minLength 1 */
  status?: string;
  group?: string;
  assignee?: string;
  tag?: string;
  ready?: boolean;
  blocked?: boolean;
  unassigned?: boolean;
  ungrouped?: boolean;
  /**
   * @min 1
   * @max 500
   * @default 200
   */
  limit?: number;
  /**
   * @minLength 1
   * @maxLength 4096
   */
  cursor?: string;
}

export type ListTasksOkEnum = true;

export interface ListTasksParams {
  /** @maxLength 4096 */
  search?: string;
  /** @minLength 1 */
  status?: string;
  group?: string;
  assignee?: string;
  tag?: string;
  ready?: boolean;
  blocked?: boolean;
  unassigned?: boolean;
  ungrouped?: boolean;
  /**
   * @min 1
   * @max 500
   * @default 200
   */
  limit?: number;
  /**
   * @minLength 1
   * @maxLength 4096
   */
  cursor?: string;
}

export type CreateTaskOkEnum = true;

export type GetTaskOkEnum = true;

export interface GetTaskParams {
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
}

export type UpdateTaskOkEnum = true;

export interface UpdateTaskParams {
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
}

export type MoveTaskOkEnum = true;

export interface MoveTaskParams {
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
}

export type ClaimTaskOkEnum = true;

export interface ClaimTaskParams {
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
}

export type ReleaseTaskOkEnum = true;

export interface ReleaseTaskParams {
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
}

export type GetTaskListOkEnum = true;

export interface GetTaskListParams {
  status?: string;
  group?: string;
  assignee?: string;
  parent?: string | number;
  tag?: string;
  /** @maxLength 4096 */
  search?: string;
  ready?: boolean;
  all?: boolean;
  sort?: SortEnum;
}

export type SortEnum = "id" | "board";

export type GetTaskListParams1SortEnum = "id" | "board";

export type GetTaskDocumentOkEnum = true;

export interface GetTaskDocumentParams {
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
}

export type GetTaskMarkdownOkEnum = true;

export interface GetTaskMarkdownParams {
  field: FieldEnum;
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
}

export type FieldEnum = "description" | "summary";

export type GetTaskMarkdownParams1FieldEnum = "description" | "summary";

export type GetTaskLinksOkEnum = true;

export interface GetTaskLinksParams {
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
}

export type GetTaskTreeOkEnum = true;

export interface GetTaskTreeParams {
  /**
   * @min 0
   * @max 100
   * @default 3
   */
  depth?: number;
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
}

export type GetGroupsOkEnum = true;

export type GetOverviewOkEnum = true;

export interface GetOverviewParams {
  /**
   * @min 1
   * @max 100
   * @default 5
   */
  limit?: number;
  /**
   * @maxItems 100
   * @minItems 1
   */
  reviewStatuses?: string[];
  /**
   * @exclusiveMin 0
   * @max 9007199254740991
   */
  rootId?: number;
}

export type ValidateProjectOkEnum = true;

export type ChangeDependencyOkEnum = true;

export interface ChangeDependencyParams {
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
}

export type ListCommentsOkEnum = true;

export interface ListCommentsParams {
  author?: string;
  /** @maxLength 4096 */
  search?: string;
  /**
   * @min 1
   * @max 100
   * @default 20
   */
  limit?: number;
  /**
   * @minLength 1
   * @maxLength 4096
   */
  cursor?: string;
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
}

export type AddCommentOkEnum = true;

export interface AddCommentParams {
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
}

export type GetCommentOkEnum = true;

export interface GetCommentParams {
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
  /** @pattern ^cmt_[a-f0-9]{32}$ */
  commentId: string;
}

export type ListLogsOkEnum = true;

export interface ListLogsParams {
  author?: string;
  /** @maxLength 4096 */
  search?: string;
  /**
   * @min 1
   * @max 100
   * @default 20
   */
  limit?: number;
  /**
   * @minLength 1
   * @maxLength 4096
   */
  cursor?: string;
  kind?: KindEnum;
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
}

export type KindEnum =
  | "progress"
  | "decision"
  | "execution"
  | "error"
  | "summary";

export type ListLogsParams1KindEnum =
  | "progress"
  | "decision"
  | "execution"
  | "error"
  | "summary";

export type AddLogOkEnum = true;

export interface AddLogParams {
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
}

export type GetLogOkEnum = true;

export interface GetLogParams {
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
  /** @pattern ^log_[a-f0-9]{32}$ */
  logId: string;
}

export type GetContextForProjectOkEnum = true;

export interface GetContextForProjectParams {
  /** Имя из реестра или идентификатор проекта */
  project: string;
}

export type GetBoardForProjectOkEnum = true;

export interface GetBoardForProjectParams {
  /** @maxLength 4096 */
  search?: string;
  /** @minLength 1 */
  status?: string;
  group?: string;
  assignee?: string;
  tag?: string;
  ready?: boolean;
  blocked?: boolean;
  unassigned?: boolean;
  ungrouped?: boolean;
  /**
   * @min 1
   * @max 500
   * @default 200
   */
  limit?: number;
  /**
   * @minLength 1
   * @maxLength 4096
   */
  cursor?: string;
  /** Имя из реестра или идентификатор проекта */
  project: string;
}

export type ListTasksForProjectOkEnum = true;

export interface ListTasksForProjectParams {
  /** @maxLength 4096 */
  search?: string;
  /** @minLength 1 */
  status?: string;
  group?: string;
  assignee?: string;
  tag?: string;
  ready?: boolean;
  blocked?: boolean;
  unassigned?: boolean;
  ungrouped?: boolean;
  /**
   * @min 1
   * @max 500
   * @default 200
   */
  limit?: number;
  /**
   * @minLength 1
   * @maxLength 4096
   */
  cursor?: string;
  /** Имя из реестра или идентификатор проекта */
  project: string;
}

export type CreateTaskForProjectOkEnum = true;

export interface CreateTaskForProjectParams {
  /** Имя из реестра или идентификатор проекта */
  project: string;
}

export type GetTaskForProjectOkEnum = true;

export interface GetTaskForProjectParams {
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
  /** Имя из реестра или идентификатор проекта */
  project: string;
}

export type UpdateTaskForProjectOkEnum = true;

export interface UpdateTaskForProjectParams {
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
  /** Имя из реестра или идентификатор проекта */
  project: string;
}

export type MoveTaskForProjectOkEnum = true;

export interface MoveTaskForProjectParams {
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
  /** Имя из реестра или идентификатор проекта */
  project: string;
}

export type ClaimTaskForProjectOkEnum = true;

export interface ClaimTaskForProjectParams {
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
  /** Имя из реестра или идентификатор проекта */
  project: string;
}

export type ReleaseTaskForProjectOkEnum = true;

export interface ReleaseTaskForProjectParams {
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
  /** Имя из реестра или идентификатор проекта */
  project: string;
}

export type GetTaskListForProjectOkEnum = true;

export interface GetTaskListForProjectParams {
  status?: string;
  group?: string;
  assignee?: string;
  parent?: string | number;
  tag?: string;
  /** @maxLength 4096 */
  search?: string;
  ready?: boolean;
  all?: boolean;
  sort?: SortEnum1;
  /** Имя из реестра или идентификатор проекта */
  project: string;
}

export type SortEnum1 = "id" | "board";

export type GetTaskListForProjectParams1SortEnum = "id" | "board";

export type GetTaskDocumentForProjectOkEnum = true;

export interface GetTaskDocumentForProjectParams {
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
  /** Имя из реестра или идентификатор проекта */
  project: string;
}

export type GetTaskMarkdownForProjectOkEnum = true;

export interface GetTaskMarkdownForProjectParams {
  field: FieldEnum1;
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
  /** Имя из реестра или идентификатор проекта */
  project: string;
}

export type FieldEnum1 = "description" | "summary";

export type GetTaskMarkdownForProjectParams1FieldEnum =
  | "description"
  | "summary";

export type GetTaskLinksForProjectOkEnum = true;

export interface GetTaskLinksForProjectParams {
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
  /** Имя из реестра или идентификатор проекта */
  project: string;
}

export type GetTaskTreeForProjectOkEnum = true;

export interface GetTaskTreeForProjectParams {
  /**
   * @min 0
   * @max 100
   * @default 3
   */
  depth?: number;
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
  /** Имя из реестра или идентификатор проекта */
  project: string;
}

export type GetGroupsForProjectOkEnum = true;

export interface GetGroupsForProjectParams {
  /** Имя из реестра или идентификатор проекта */
  project: string;
}

export type GetOverviewForProjectOkEnum = true;

export interface GetOverviewForProjectParams {
  /**
   * @min 1
   * @max 100
   * @default 5
   */
  limit?: number;
  /**
   * @maxItems 100
   * @minItems 1
   */
  reviewStatuses?: string[];
  /**
   * @exclusiveMin 0
   * @max 9007199254740991
   */
  rootId?: number;
  /** Имя из реестра или идентификатор проекта */
  project: string;
}

export type ValidateProjectForProjectOkEnum = true;

export interface ValidateProjectForProjectParams {
  /** Имя из реестра или идентификатор проекта */
  project: string;
}

export type ChangeDependencyForProjectOkEnum = true;

export interface ChangeDependencyForProjectParams {
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
  /** Имя из реестра или идентификатор проекта */
  project: string;
}

export type ListCommentsForProjectOkEnum = true;

export interface ListCommentsForProjectParams {
  author?: string;
  /** @maxLength 4096 */
  search?: string;
  /**
   * @min 1
   * @max 100
   * @default 20
   */
  limit?: number;
  /**
   * @minLength 1
   * @maxLength 4096
   */
  cursor?: string;
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
  /** Имя из реестра или идентификатор проекта */
  project: string;
}

export type AddCommentForProjectOkEnum = true;

export interface AddCommentForProjectParams {
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
  /** Имя из реестра или идентификатор проекта */
  project: string;
}

export type GetCommentForProjectOkEnum = true;

export interface GetCommentForProjectParams {
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
  /** @pattern ^cmt_[a-f0-9]{32}$ */
  commentId: string;
  /** Имя из реестра или идентификатор проекта */
  project: string;
}

export type ListLogsForProjectOkEnum = true;

export interface ListLogsForProjectParams {
  author?: string;
  /** @maxLength 4096 */
  search?: string;
  /**
   * @min 1
   * @max 100
   * @default 20
   */
  limit?: number;
  /**
   * @minLength 1
   * @maxLength 4096
   */
  cursor?: string;
  kind?: KindEnum1;
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
  /** Имя из реестра или идентификатор проекта */
  project: string;
}

export type KindEnum1 =
  | "progress"
  | "decision"
  | "execution"
  | "error"
  | "summary";

export type ListLogsForProjectParams1KindEnum =
  | "progress"
  | "decision"
  | "execution"
  | "error"
  | "summary";

export type AddLogForProjectOkEnum = true;

export interface AddLogForProjectParams {
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
  /** Имя из реестра или идентификатор проекта */
  project: string;
}

export type GetLogForProjectOkEnum = true;

export interface GetLogForProjectParams {
  /**
   * Положительный безопасный целочисленный ID задачи
   * @min 1
   * @max 9007199254740991
   */
  id: number;
  /** @pattern ^log_[a-f0-9]{32}$ */
  logId: string;
  /** Имя из реестра или идентификатор проекта */
  project: string;
}

export interface WatchEventsForProjectParams {
  /** Имя из реестра или идентификатор проекта */
  project: string;
}
